#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ### adding default font and keymap
    add_binary loadkeys
    add_file /usr/share/kbd/consolefonts/ter-v16n.psf.gz
    add_file /usr/share/kbd/consolefonts/ter-v32n.psf.gz
    add_file /usr/share/kbd/keymaps/i386/qwerty/us.map.gz
    add_full_dir /usr/share/kbd/keymaps/i386/include
    add_full_dir /usr/share/kbd/keymaps/include
}

help ()
{
cat <<HELPEOF
  This hook sets up stripped down base for for latest image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
