#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
  add_full_dir /var/cache/pacman/pkg
}

help ()
{
cat<<HELPEOF
  This hook includes /var/cache/pacman/pkg.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
