#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    map add_binary hwclock tzselect zic zdump
    map add_full_dir /usr/share/zoneinfo /usr/share/zoneinfo-leaps
    add_file /usr/bin/archboot-clock.sh /usr/bin/clock
}

help ()
{
cat<<HELPEOF
  This hook includes the timezone data on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
