#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_all_modules '/hv/hv_*'
}

help ()
{
cat<<HELPEOF
  This hook includes hypervisor modules on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
