#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    map add_binary kexec vmcore-dmesg
}

help ()
{
cat<<HELPEOF
  This hook includes kexec on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
