#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    add_binary lshw
    for i in manuf oui pnpid; do
      add_file "/usr/share/lshw/${i}.txt"
    done
    add_file /usr/share/lshw/pnpid.txt
}

help ()
{
cat <<HELPEOF
  This hook will add lshw to your archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
