#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    local symlink
    ### from thin-provisioning-tools
    add_binary pdata_tools
    for symlink in cache_{check,dump,metadata_size,repair,restore} thin_{check,delta,dump,ls,metadata_size,repair,restore,rmap,trim}; do
        add_symlink "/usr/bin/${symlink}" pdata_tools
    done
    map add_binary lvmdump lvmconfig vgimportclone fsadm vgcfgbackup vgcfgrestore vgchange \
          vgck vgconvert vgcreate vgdisplay vgexport vgextend vgimport vgmerge vgmknodes \
          vgreduce vgremove vgrename vgs vgscan vgsplit pvchange pvck pvcreate pvdisplay \
          pvmove pvremove pvresize pvs pvscan lvchange lvconvert lvcreate lvdisplay \
          lvextend lvmdiskscan lvmsadc lvmsar lvreduce lvremove lvrename lvresize lvs \
          lvscan lvm_import_vdo lvmdevices lvmpolld vgimportdevices
    map add_dir /etc/lvm/backup /etc/lvm/archive
    for i in /usr/lib/liblvm*; do
        add_file "${i}"
    done
    add_file /etc/lvm/lvm.conf
}

help ()
{
cat<<HELPEOF
  This hook adds complete lvm2 to archboot image, 
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
