#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_all_modules -f 'dm-' 'drivers/md/*'
    map add_binary mdmon mdadm
    add_file /etc/mdadm.conf
    add_file /usr/share/mdadm/mdcheck
}

help ()
{
cat<<HELPEOF
  This hook adds complete mdadm to archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
