#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary nvim
    map add_full_dir /usr/share/nvim
    map add_file /usr/share/licenses/neovim/LICENSE.txt
    # add lastplace plugin:
    # https://github.com/neovim/neovim/issues/16339
    add_file /usr/share/archboot/nvim/nvim-lastplace.lua /usr/share/nvim/runtime/plugin/nvim-lastplace.lua
}

help ()
{
cat<<HELPEOF
  This hook includes neovim on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
