#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    map add_binary arping clockdiff tracepath ssh genl \
      ifstat ctstat rtstat lnstat nstat rtacct rtmon ss tc bridge \
      dcb devlink rdma tipc vdpa ethtool elinks weechat brctl
    # add iproute 2, add openssl helper libraries
    map add_full_dir /usr/lib/tc /usr/share/tc /etc/iproute2 /usr/lib/engines
    # add dnssec-anchors
    add_file /etc/trusted-key.key
    # add weechat plugins and defaults
    _PLUGINS="alias exec lua relay typing buflist fifo irc xfer charset fset logger script trigger"
    for i in ${_PLUGINS}; do
      add_file "/usr/lib/weechat/plugins/${i}.so"
    done
    add_file /usr/share/archboot/net/etc/weechat/irc.conf /etc/weechat/irc.conf
    add_file /usr/share/archboot/net/etc/weechat/weechat.conf /etc/weechat/weechat.conf
    add_file /usr/share/archboot/net/etc/profile.d/weechat.sh /etc/profile.d/weechat.sh
    # add elinks defaults
    add_file /usr/share/archboot/net/etc/elinks/bookmarks /etc/elinks/bookmarks
    add_file /usr/share/archboot/net/etc/profile.d/elinks.sh /etc/profile.d/elinks.sh
    # fixing licenses
    map add_file /usr/share/licenses/krb5/LICENSE /usr/share/licenses/openssh/LICENCE \
        /usr/share/licenses/openssl/LICENSE.txt /usr/share/licenses/sqlite/license.txt \
        /usr/share/licenses/dnssec-anchors/LICENSE
}

help ()
{
cat<<HELPEOF
  This hook includes the additional network tools on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
