#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    _APPS="arping clockdiff tracepath ssh arpd \
      genl ifstat ctstat rtstat lnstat nstat rtacct rtmon ss tc \
      bridge dcb devlink rdma tipc vdpa ethtool elinks brctl"
    for i in ${_APPS}; do
        rm /usr/bin/"${i}"
    done
}

help ()
{
cat<<HELPEOF
  This hook cleans up binaries of archboot_net hook,
  for update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
