#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    add_all_modules -f 'media' '/platform/'
}

help ()
{
cat<<HELPEOF
  This hook adds the necessary modules for a platform device.
HELPEOF
}
 
# vim: set ft=sh ts=4 sw=4 et:
