#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary smartctl smartd update-smart-drivedb
    map add_file /etc/conf.d/smartd /etc/smartd.conf
}

help ()
{
cat<<HELPEOF
  This hook includes smartmontools on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
