#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! rg -qw 'archboot' /etc/hostname && return
    _install_files
    rm /usr/bin/{addpart,attr,b2sum,blk{discard,pr,zone},blockdev,bunzip2,\
bz{cat,diff,grep,ip2,ip2recover,more},cal,capsh,ch{acl,con,cpu,mem,oom,rt},\
cfdisk,cksum,col{,crt,rm,umn},ctrlaltdel,delpart,depmod,diff,\
dir{name,colors},dmesg,eject,egrep,fallocate,fadvise,\
fdisk,fgrep,file,fincore,findmnt,flock,free,fuser,\
get{cap,facl,fattr,opt,pcaps},gunzip,gzexe,hardlink,hdparm,hexdump,\
id,ionice,ipc{mk,rm,s},irqtop,isosize,join,keyctl,last{,b},ldattach,ldd,\
linux{32,64},logname,look,losetup,ls{cpu,fd,ipc,irq,locks,logins,mem,ns},\
lz4{,c,cat},lz{cat,cmp,diff,egrep,fgrep,grep,less,more,ma,madec,mainfo,op},\
mcookie,md5sum,mesg,mkfs,modinfo,namei,new{grp,gidmap,uidmap},\
nsenter,partx,paste,pidwait,pinky,\
pg,pipesz,pkill,pmap,prlimit,prtstat,pslog,\
pstree,pwdx,pzstd,readprofile,rename,renice,request-key,\
resizepart,reset,rev,rtcwake,run{con,user},script{,live,replay},sdparm,\
set{arch,cap,facl,fattr,priv,sid,term},sfdisk,slabtop,su,swap{label,off,on},\
sysctl,taskset,tload,tput,tunelp,uclampset,ul,\
un{ame26,compress,lz4,lzma,share,xz,zstd},utmpdump,uuidd,\
uuidgen,uuidparse,vigr,vipw,vmstat,w,wall,watch,wdctl,whereis,\
write,xargs,xz{,cat,cmp,dec,grep,egrep,fgrep},z{cat,cmp,diff,egrep,fgrep,force,\
grep,less,more,new,ramctl},zstd{cat,grep,less,mt}}
    if [[ "${_RUNNING_ARCH}" == "x86_64" ]]; then
        rm /usr/bin/{archlinux-userland-fs-cmp,i386,x86_64,peekfd,waitpid}
    fi
    if [[ "${_RUNNING_ARCH}" == "aarch64" ]]; then
        rm /usr/bin/{archlinux-userland-fs-cmp,peekfd}
    fi
    if [[ "${_RUNNING_ARCH}" == "riscv64" ]]; then
        rm /usr/bin/waitpid
    fi
}

