#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary head id cksum tail test uptime w who whoami xargs \
          swapon uniq seq fdisk sfdisk cfdisk parted free less \
          chgrp chown dmesg egrep fgrep stty hdparm sync \
          dirname chroot expr bzip2 su sdparm tput bsdcpio \
          losetup mkfifo mknod readlink lzmadec lzop xz last wall mesg utmpdump \
          xzdec switch_root pivot_root chcpu ctrlaltdel gdisk sgdisk cgdisk fixparts findmnt \
          lsfd lsblk swaplabel cal chrt col colcrt colrm column fallocate flock getopt \
          ionice ipcmk ipcrm ipcs swapoff look lscpu mcookie namei prlimit rename \
          renice rev script scriptreplay setarch setsid setterm taskset ul unshare \
          uuidgen whereis write addpart delpart ldattach partx readprofile rtcwake uuidd \
          sysctl pidwait pkill pmap pwdx slabtop tload vmstat watch eject keyctl request-key \
          tac sulogin resizepart lslocks wdctl zless zgrep fold hexdump ldd \
          shred blockdev blkdiscard newgrp nsenter runuser vigr vipw diff depmod \
          linux32 linux64 lsmod lzcat lzcmp lzdiff lzegrep lzfgrep lzgrep lzegrep \
          lzless lzmore lzma modinfo reset unlzma unxz xzcat lastb \
          blkzone chmem choom fincore hardlink irqtop lsipc lsirq lslogins lsmem lsns mkfs \
          scriptlive setpriv  uclampset uname26 uuidparse zramctl [ b2sum base32 base64 \
          basenc chcon comm csplit dircolors expand factor fmt hostid join link \
          logname md5sum nice nl nohup nproc numfmt paste pathchk pinky pr printenv ptx realpath \
          runcon sha1sum sha224sum sha256sum sha384sum sha512sum shuf split stdbuf sum timeout truncate \
          tsort unexpand unlink users vdir fuser prtstat pslog pstree newgid_map newuid_map \
          lzmainfo xzcmp xzgrep xzegrep xzfgrep gzexe uncompress zcmp zdiff zegrep zfgrep zforce zmore znew \
          bunzip2 bzcat bzdiff bzgrep bzip2recover bzmore chacl getfacl setfacl attr getfattr \
          setfattr pzstd unzstd zstdcat zstdgrep zstdless zstdmt lz4 lz4c lz4cat unlz4 gunzip zcat wipe \
          capsh getcap getpcaps setcap file blkpr fadvise isosize pg pipesz tunelp

    [[ "$(uname -m)" == "x86_64" ]] && _map _binary i386 x86_64 peekfd waitpid
    [[ "$(uname -m)" == "aarch64" ]] && _binary peekfd
    [[ "$(uname -m)" == "riscv64" ]] && _map _binary waitpid
    ### add C.UTF-8 locale
    _dir /usr/lib/locale
    _full_dir /usr/lib/locale/C.utf8
    ### add custom locale
    [[ -e "/usr/lib/locale/locale-archive" ]] && _file /usr/lib/locale/locale-archive
    
    ### add shadow
    _map _binary groups chage chfn chsh expiry faillog gpasswd lastlog \
          chgpasswd chpasswd groupadd groupdel groupmems groupmod grpck grpconv grpunconv \
          newusers pwck pwconv pwunconv useradd userdel usermod sg getsubids

    ### fix licenses
    _map _file /usr/share/licenses/file/COPYING /usr/share/licenses/bzip2/LICENSE \
                 /usr/share/licenses/hdparm/LICENSE.TXT /usr/share/licenses/ncurses/COPYING \
                 /usr/share/licenses/sdparm/LICENSE /usr/share/licenses/zlib/LICENSE
}

# vim: set ft=sh ts=4 sw=4 et:
