#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ### acpi
    _all_mods '/acpi/'
    ### add pcspkr
    [[ "${_RUNNING_ARCH}" == "x86_64" ]] && _mod pcspkr
    ### platform modules
    _all_mods -f 'media' '/platform/'
    ### add init modules
    _map _mod zram btrfs zstd
    ### keyboard modules
    _all_mods -f '_cs|bcma-hcd|ssb-hcd' '/usb/host'
    _all_mods '/pinctrl/'
    _all_mods '/hid/hid-(alps|apple|asus|belkin|cherry|chicony|corsair|elan|generic|hyperv|kensignton|lenovo|logitech|magicmouse|microsoft|razer|redragon|roccat|samsung|sony|speedlink|steelseries)'
    _mod usbhid
    _all_mods -f 'parkbd' '/input/serio|mouse|keyboard/(applespi|atkbd)'
    _all_mods -f '9pnet|bluetooth|fs' 'virtio'
}

