#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# created by Tobias Powalowski <tpowa@archlinux.org>

_run() {
    ### init modules
    # isofs needed for aarch64, alias is not working anymore 2024/09/23
    _map _mod vfat iso9660 isofs nls_cp437 nls_ascii cdrom exfat
}
