#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ### adding default font and keymap
    _binary loadkeys
    _file /usr/share/kbd/consolefonts/ter-v16n.psf.gz
    _file /usr/share/kbd/consolefonts/ter-v32n.psf.gz
    _file /usr/share/kbd/keymaps/i386/qwerty/us.map.gz
    _full_dir /usr/share/kbd/keymaps/i386/include
    _full_dir /usr/share/kbd/keymaps/include
}

# vim: set ft=sh ts=4 sw=4 et:
