#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# created by Tobias Powalowski <tpowa@archlinux.org>

_run() {
    ### init modules
    _map _mod vfat iso9660 nls_cp437 nls_ascii cdrom exfat
}
