#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # turn on initrd mode
    : > "${_ROOTFS}"/etc/initrd-release
    _map _dir /mnt/{cdrom,ventoy,efi}
    # dialog colours
    _file_rename "/usr/share/archboot/base/etc/dialogrc" "/etc/dialogrc"
    # systemd
    _map _binary /usr/lib/systemd/systemd{,-battery-check,-executor,-bsod,-journald,\
-shutdown,-sulogin-shell,-sysctl,-sysroot-fstab-check,-udevd} lspci
    _map _file /usr/lib/systemd/{lib*,system-generators/systemd-fstab-generator} /usr/share/hwdata/pci.ids
    # only take services from systemd package
    pacman -Sy &>"${_NO_LOG}"
    for i in $(pacman -Ql systemd | rg '/usr/lib/systemd/system/.' | choose 1); do
        _file "${i}"
    done
    _map _file /usr/lib/sysusers.d/{arch,basic}.conf /usr/lib/libbpf.so
    # disable systemd services:
    for i in lvm2-{lvmpolld,monitor} systemd-{boot,random-seed,sysusers\
,tmpfiles-setup{,-dev,-dev-early},update-{done,utmp},vconsole-setup}; do
        _symlink "/etc/systemd/system/${i}.service" /dev/null
    done
    # disable systemd sockets:
    _symlink /etc/systemd/system/lvm2-lvmpolld.socket /dev/null
    # add udev
    _map _file /usr/lib/udev/rules.d/{50-udev-default,60-persistent-storage,64-btrfs,80-drivers,99-systemd}.rules \
    /usr/lib/udev/{ata,scsi}_id
    # run initrd service
    _file /usr/lib/archboot/cpio/init.sh
    _file_rename /usr/share/archboot/base/etc/systemd/system/archboot-init.service \
                 /etc/systemd/system/archboot-init.service
    _file_rename /usr/share/archboot/base/etc/systemd/system/initrd-cleanup.service \
                 /etc/systemd/system/initrd-cleanup.service
}
