#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary addpart attr blk{discard,pr,zone} blockdev bunzip2 \
                 bz{cat,diff,grep,ip2,ip2recover,more} cal capsh captoinfo ch{acl,con,cpu,mem,oom,rt} \
                 cfdisk col{,crt,rm,umn} ctrlaltdel delpart diff \
                 depmod dmesg eject egrep fallocate fadvise \
                 fdisk fgrep file fincore findmnt flock free fuser \
                 get{cap,facl,fattr,opt,pcaps} gunzip gzexe hardlink hdparm hexdump \
                 info{cmp,tocap} ionice ipc{mk,rm,s} irqtop isosize keyctl last{,b} ldattach ldd \
                 linux{32,64} look losetup ls{cpu,fd,ipc,irq,locks,logins,mem,ns} \
                 lz4{,c,cat} lz{cat,cmp,diff,egrep,fgrep,grep,less,more,ma,madec,mainfo,op} \
                 mcookie md5sum mesg mkfs modinfo namei new{grp,gidmap,uidmap} \
                 ncursesw6-config nsenter partx pidwait \
                 pg pipesz pkill pmap prlimit prtstat pslog \
                 pstree pwdx pzstd readprofile rename renice request-key \
                 resizepart reset rev rtcwake run{con,user} script{,live,replay} sdparm \
                 set{arch,cap,facl,fattr,priv,sid,term} sfdisk slabtop \
                 su swap{label,off,on} sysctl tabs taskset tic tload \
                 toe tput tunelp uclampset ul \
                 un{ame26,compress,lz4,lzma,share,xz,zstd} utmpdump \
                 uuidd uuidgen uuidparse vigr vipw vmstat w waitpid wall watch wdctl whereis \
                 write xargs xz{,cat,cmp,dec,grep,egrep,fgrep} \
                 z{cat,cmp,diff,egrep,fgrep,force,grep,less,more,new,ramctl} zstd{cat,grep,less,mt}
    [[ "${_RUNNING_ARCH}" == "x86_64" ]] && _map _binary archlinux-userland-fs-cmp i386 x86_64 peekfd
    [[ "${_RUNNING_ARCH}" == "aarch64" ]] && _map _binary archlinux-userland-fs-cmp peekfd
    # add file magic file
    _file /usr/share/file/misc/magic.mgc
    # add shadow
    _map _binary ch{age,fn,sh} expiry {fail,last}log \
          {chg,ch,g}passwd group{add,del,mems,mod} grp{ck,conv,unconv} \
          newusers pw{ck,conv,unconv} user{add,del,mod} sg getsubids
    # add ncurses libs
    _map _file /usr/lib/libncurses*.so
}

