#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! grep -qw 'archboot' /etc/hostname && return
    _install_files
    rm /usr/bin/{3cpio,blkid,gzip,journalctl,less,lsmod,mkfs.btrfs,\
mountpoint,setfont,sulogin,systemctl}
}

# vim: set ft=sh ts=4 sw=4 et:
