#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! rg -qw 'archboot' /etc/hostname && return
    # remove pacman-init.service
    rm -f /tmp/etc/systemd/system/multi-user.target.wants/pacman-init.service
    rm -f /tmp/etc/systemd/system/pacman-init.service
    # add created gpg keyring
    cp -ar /etc/pacman.d/gnupg /tmp/etc/pacman.d
    _install_files
    rm /usr/bin/{login,nologin,mount.nfs{,4},umount.nfs{,4},loadkeys,dbus-{cleanup-sockets,\
daemon,launch,monitor,run-session,send,test-tool,update-activation-environment,uuidgen},\
kernel-install,systemctl,systemd-{analyze,ask-password,cat,cgls,cgtop,delta,detect-virt,escape,firstboot,\
hwdb,inhibit,machine-id-setup,mount,notify,nspawn,path,resolve,run,umount,socket-activate,\
stdio-bridge,sysusers,tty-ask-password-agent,repart,creds,cryptenroll,dissect,id128,sysext},\
{bus,coredump,locale,login,machine,network,hostname,timedate,userdb,home,oom,portable}ctl,zoxide}
}

