#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # remove conflicting grub, rpcbind and ukify files
    tar -C / --exclude=etc/systemd/system/multi-user.target.wants/remote-fs.target \
--exclude=usr/share/bash-completion/completions/grub \
--exclude=usr/lib/{modules-load.d/cdrecord.conf,systemd/{system/{blk-availability.service,lvm2*,\
rpcbind*,sysinit.target.wants/lvm2*},ukify},sysusers.d/rpcbind*,tmpfiles.d/rpcbind*} \
--hard-dereference -cpf - \
etc/{ca-certificates/extracted,default,pam.d,pinentry,profile.d,security,skel,ssl/certs,sysctl.d,systemd,tpm2-tss,xdg} \
usr/lib/{coreutils,cryptsetup,gconv,modules-load.d,p11-kit,pam.d,pkcs11,security,sysctl.d,systemd,sysusers.d,tmpfiles.d,udev} \
usr/share/{bash-completion,dbus-1,factory,hwdata,i18n/locales,makepkg,nano,pacman/keyrings,polkit-1,readline,systemd,terminfo} \
| tar -C "${_ROOTFS}" -xpf -
    # only run on archboot container
    if grep -qw 'archboot' /etc/hostname; then
        _map _binary locale{-gen,def}
        _map _file /etc/locale.gen /usr/share/locale/locale.alias
        # only support UTF-8
        _file /usr/share/i18n/charmaps/UTF-8.gz
        tar -C / --exclude=var/lib/pacman/local/{base-*-[0-9]*,binutils-*-[0-9]*,\
cdrtools-*-[0-9]*,db5.3-*-[0-9]*,db-*-[0-9]*,duktape-*-[0-9]*,edk2-shell-*-[0-9]*,fuse-common-*-[0-9]*,gc-*-[0-9]*,\
gdbm-*-[0-9]*,gettext-*-[0-9]*,groff-*-[0-9]*,grub-*-[0-9]*,jansson-*-[0-9]*,\
libbsd-*-[0-9]*,libburn-*-[0-9]*,libev-*-[0-9]*,libisoburn-*-[0-9]*,libisofs-*-[0-9]*,\
libksba-*-[0-9]*,libmd-*-[0-9]*,libldap-*-[0-9]*,libnfnetlink-*-[0-9]*,libnetfilter_conntrack-*-[0-9]*,\
libnftnl-*-[0-9]*,libpcap-*-[0-9]*,libpipeline-*-[0-9]*,libsasl-*-[0-9]*,libsysprof-capture-*-[0-9]*,\
libwbclient-*-[0-9]*,limine-*-[0-9]*,linux-api-headers-*-[0-9]*,memtest86+-*-[0-9]*,\
memtest86+-efi-*-[0-9]*,memtest-*-[0-9]*,mtools-*-[0-9]*,polkit-*-[0-9]*,python-*-[0-9]*,python-pefile-*-[0-9]*,\
refind-*-[0-9]*,rpcbind-*-[0-9]*,systemd-ukify-*-[0-9]*} \
--exclude=usr/share/locale/*/{grub*,binutils*,gdbm*,bfd*,gettext*,gas*,gold*,gprof*,ld*,opcodes*} \
--hard-dereference -cpf - \
usr/share/{locale/{be,bg,cs,da,de,en_US,el,es,fi,fr,hu,it,lt,lv,mk,nl,nn,pl,pt,ro,ru,sk,sr,sv,uk},i18n/locales} \
var/lib/pacman/local \
| tar -C "${_ROOTFS}" -xpf -
    fi
    _map _binary agetty archlinux-keyring-wkd-sync awk basename bsdtar \
                 {bus,boot,coredump,hostname,journal,locale,login,machine,network,\
system,timedate,userdb,home,oom,portable}ctl certutil chmod clear cmsutil crlutil curl date \
                 dbus-{broker{,-launch},cleanup-sockets,daemon,launch,monitor,run-session,send,test-tool,\
update-activation-environment,uuidgen} dd df dir du false gawk gpg{,-agent,conf,-connect-agent} \
                 gpgme-{tool,json} insmod install kernel-install kill{,all} loadkeys ldconfig \
                 login makepkg mktemp mkhomedir_helper modutil more mount.ddi mount.nfs{,4} \
                 nano nologin nss-config od p11-kit pk12util pam_timestamp_check pacman{,-conf,-key,-db-upgrade} \
                 passwd pgrep pidof pinentry{,-curses} printf ps pwd rmdir tr true \
                 repo-{add,elephant,remove} rbash rmmod secret-tool shlibsign sign{tool,ver} sort \
                 ssltap stat symkeyutil systemd-{ac-power,analyze,ask-password,cat,cgls,cgtop,confextdelta,\
detect-virt,escape,firstboot,hwdb,inhibit,machine-id-setup,mount,notify,nspawn,path,resolve,repartrun,\
socket-activate,stdio-bridge,sysusers,tty-ask-password-agent,umount,creds,cryptenroll,dissect,id128,sysext} \
                 tar tee testpkg top touch trust tty unix_{chkpwd,update} /usr/lib/dbus-1.0/dbus-daemon-launch-helper \
                 umount.nfs{,4} update-ca-trust vercmp wc yes zstd
    # use patched aarch64 pacman-key
    # https://archlinuxarm.org/forum/viewtopic.php?f=15&t=16701
    if [[ "${_RUNNING_ARCH}" == "aarch64" ]]; then
        _install_files
        _file_rename "/usr/share/archboot/patches/pacman-key-aarch64" "/usr/bin/pacman-key"
    fi
    # add nano
    _file_rename /etc/nanorc /etc/nanorc
    # add syntax highlighting
    echo "include \"/usr/share/nano/*.nanorc\"" >> "${_ROOTFS}/etc/nanorc"
    ### add machine-id
    : > "${_ROOTFS}"/etc/machine-id
    # add terminfo
    _symlink /usr/lib/terminfo ../share/terminfo
    # add needed files from running system
    _map _file /etc/{crypttab,fstab,host.conf,hosts,inputrc,mke2fs.conf,nsswitch.conf,\
protocols,request-key.conf,securetty,services}
    for i in issue tmpfiles.d/var.conf; do
        _file_rename "/usr/share/archboot/base/etc/${i}" "/etc/${i}"
    done
    # fixing network support from glibc
    _map _file /usr/lib/{libnss_files.so.2,libnss_dns.so.2}
    ## add pam and shadow
    _map _file /etc/{environment,login.defs}
    # systemd files
    _map _dir /etc/tmpfiles.d /etc/modules-load.d /etc/binfmt.d
    _file_rename /usr/share/archboot/base/etc/locale.conf /etc/locale.conf
    _file_rename /usr/share/archboot/base/etc/vconsole.conf /etc/vconsole.conf
    _file_rename /usr/share/archboot/base/etc/systemd/system/systemd-user-sessions.service \
                 /etc/systemd/system/systemd-user-sessions.service
    _file_rename /usr/share/archboot/base/etc/systemd/system/getty@.service \
                 /etc/systemd/system/getty@.service
    _file_rename /usr/share/archboot/base/etc/systemd/system/serial-getty@.service \
                 /etc/systemd/system/serial-getty@.service
    _file_rename /usr/share/archboot/base/etc/systemd/system/windowkeys.service \
                 /etc/systemd/system/windowkeys.service
    _file_rename /usr/share/archboot/base/etc/systemd/journald.conf.d/fw-tty12.conf \
                 /etc/systemd/journald.conf.d/fw-tty12.conf
    _file_rename /usr/bin/archboot-detect-vconsole.sh \
                 /usr/bin/detect-vconsole.sh
    _file_rename /usr/share/archboot/base/etc/systemd/system/detect-vconsole.service \
                 /etc/systemd/system/detect-vconsole.service
    _symlink /etc/systemd/system/sysinit.target.wants/detect-vconsole.service \
             /etc/systemd/system/detect-vconsole.service
    _symlink /etc/systemd/system/multi-user.target.wants/windowkeys.service \
             /etc/systemd/system/windowkeys.service
    # disable systemd targets:
    for i in remote-{veritysetup,cryptsetup} sockets timers; do
        _symlink "/etc/systemd/system/${i}.target" /dev/null
    done
    # disable systemd timers:
    for i in shadow systemd-tmpfiles-clean; do
        _symlink "/etc/systemd/system/${i}.timer" /dev/null
    done
    # disable systemd-gpt-auto-generator, errors out on initramfs usage
    _symlink /etc/systemd/system-generators/systemd-gpt-auto-generator /dev/null
    # disable lastlog
    _symlink /var/log/lastlog /dev/null
    _file_rename /usr/share/archboot/base/etc/tmpfiles.d/var.conf /etc/tmpfiles.d/var.conf
    # add missing libsystemd files
    _map _file /usr/lib/{libnss_myhostname.so.2,libnss_mymachines.so.2,libnss_resolve.so.2,libnss_systemd.so.2}
    # fix tmpfiles startup
    _map _file /usr/lib/{libnss_compat.so.2,libnsl.so.1}
    # add schedule rules file
    _file_rename /usr/share/archboot/base/etc/udev/rules.d/60-ioschedulers.rules \
                 /etc/udev/rules.d/60-ioschedulers.rules
    # add minimal vconsole
    _map _file /usr/share/kbd/keymaps/i386/{include/{qwerty-layout,compose,\
linux-with-alt-and-altgr,linux-keys-bare}.inc,qwerty/us.map.gz} \
    /usr/share/kbd/keymaps/{include/compose.latin1,i386/include/{euro{,1},windowkeys}.map.gz}
    # add swapiness sysctl config file
    _file_rename /usr/share/archboot/base/etc/sysctl.d/99-sysctl.conf /etc/sysctl.d/99-sysctl.conf
    # add pacman
    _map _dir /var/{cache/pacman/pkg,lib/pacman}
    _map _file /etc/{pacman.conf,makepkg.conf,pacman.d/mirrorlist}
    # add pacman initialization of gpg keys
    _dir /etc/pacman.d/gnupg
    _file_rename /usr/share/archboot/base/etc/systemd/system/pacman-init.service \
                 /etc/systemd/system/pacman-init.service
    # add nss p11-kit and ca certificates
    _symlink "/etc/ssl/cert.pem" "../ca-certificates/extracted/tls-ca-bundle.pem"
    _symlink "/etc/ssl/certs/ca-certificates.crt" "../../ca-certificates/extracted/tls-ca-bundle.pem"
    _map _file /usr/share/{ca-certificates/trust-source/mozilla.trust.p11-kit,p11-kit/modules/p11-kit-trust.module}
    # fix licenses
    _map _file /usr/share/licenses/{shadow/COPYING,iana-etc/LICENSE,dbus/COPYING,p11-kit/COPYING}
}

# vim: set ft=sh ts=4 sw=4 et:
