#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
  ! grep -qw 'archboot' /etc/hostname && return
  rm -r /var/cache/pacman/pkg
}

# vim: set ft=sh ts=4 sw=4 et:
