#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary hwclock tzselect zic zdump
    _map _full_dir /usr/share/{zoneinfo,zoneinfo-leaps}
    _file_rename /usr/bin/archboot-clock.sh /usr/bin/clock
}

