#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary cpupower cpufreq-bench_plot.sh
    _file /etc/defaults/cpufreq-bench.conf
}

