#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _all_mods 'md/dm-*'
    _map _binary dmsetup dmeventd blkdeactivate dmstats cryptsetup \
        integritysetup veritysetup
    _dir /dev/mapper
    _full_dir /usr/lib/device-mapper
    _map _file /usr/lib/libdevmapper*
    # cryptsetup calls pthread_create(), which dlopen()s libgcc_s.so.1
    # cryptsetup loads the legacy provider which is required for whirlpool
    _map _file /usr/lib/{libgcc_s.so.1,ossl-modules/legacy.so}
}

# vim: set ft=sh ts=4 sw=4 et:
