#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _binary dmidecode
    [[ "${_RUNNING_ARCH}" == "x86_64" ]] && _binary biosdecode
}

