#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary efivar efisecdb
}

help ()
{
cat<<HELPEOF
  This hook includes efivar on an archboot image.
HELPEOF
}

# vim: set ft=sh ts=4 sw=4 et:
