#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! grep -qw 'archboot' /etc/hostname && return
    _install_files
    rm /usr/bin/{badblocks,blkmapd,btrfs-{find-root,image,map-logical,select-super},btrfs{,ck,tune},\
chattr,chcp,cifscreds,cifs.{idmap,upcall},compile_et,debugfs,defrag.f2fs,\
dosfsck,dosfslabel,dump.{exfat,f2fs},dump{e2fs,seg},e2{freefrag,fsck,image,label,\
mmpstatus,scrub,scrub_all,undo},e4{crypt,defrag},exfatlabel,f2fs{_io,crypt},fat{label,resize},findfs,fsck,\
logsave,resize2fs,lsattr,filefrag,fsck.{btrfs,exfat,ext2,ext4,f2fs,jfs,\
msdos,vfat,xfs},fibmap.f2fs,fs{freeze,trim},getcifsacl,gpart,jfs_{debugfs,fsck,fscklog,\
logdump,mkfs,tune},ls{cp,su},mk{_cmds,cp,dosfs,e2fs,swap},mkfs.{exfat,ext2,ext4,\
f2fs,jfs,msdos,vfat,xfs},mount.{cifs,smb3},nfs{conf,dcld,idmap},nfsv4.exportd,\
nvme,parse.f2fs,resize.f2fs,rmcp,setcifsacl,sload.f2fs,\
tune.exfat,tune2fs,wipefs,xfs_{admin,bmap,copy,db,estimate,freeze,fsr,\
growfs,info,io,logprint,metadump,mdrestore,mkfile,ncheck,quota,repair,rtcp,spaceman}}
}

# vim: set ft=sh ts=4 sw=4 et:
