#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! rg -qw 'archboot' /etc/hostname && return
    _install_files
    rm /usr/bin/{badblocks,blkmapd,btrfs-{find-root,image,map-logical,select-super},btrfs{,ck,tune},\
chattr,cifscreds,cifs.{idmap,upcall},compile_et,debugfs,\
dosfsck,dosfslabel,dump.exfat,dumpe2fs,e2{freefrag,fsck,image,label,\
mmpstatus,scrub,scrub_all,undo},e4{crypt,defrag},exfatlabel,fatlabel,findfs,fsck,\
logsave,resize2fs,lsattr,filefrag,fsck.{btrfs,exfat,ext2,ext4,\
msdos,vfat,xfs},fs{freeze,trim},getcifsacl,\
mk{_cmds,dosfs,e2fs,swap},mkfs.{exfat,ext2,ext4,\
msdos,vfat,xfs},mount.{cifs,smb3},nfs{conf,dcld,idmap},nfsv4.exportd,\
nvme,setcifsacl,\
tune.exfat,tune2fs,wipefs,xfs_{admin,bmap,copy,db,estimate,freeze,fsr,\
growfs,info,io,logprint,metadump,mdrestore,mkfile,ncheck,quota,repair,rtcp,spaceman}}
}

