#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # add firmware files and licenses
    tar -C / --exclude=lib/firmware/{amd-ucode,amphion,as102*,atusb,av7110,cadence,cavium,cmmb*,cis,cpia2,cnm,\
ct*,cxgb*,cmmb*,dabusb,dpaa2,dsp56k,dvb*,edgeport,emi26,emi62,ess,f2255usb*,go7007,hfi1*,inside-secure,isdbt*,\
intel-ucode,keyspan*,korg,meson,lgs8g75*,lt9611uxc*,moxa,mts*,myri10ge*,myricom,nxp,ositech,qat*,sb16,s2250*,s5p-*,sms1*,\
rtl_bt,tdmb*,ttusb-budget,ueagle-atm,usbdux*,ti,ti-keystone,v4l*,vicam,vxge,whiteheat*,yam,yamaha,*.txt*,*README*} \
--hard-dereference -cpf - lib/firmware usr/share/licenses/linux-firmware | tar -C "${_ROOTFS}" -xpf -
}

# vim: set ft=sh ts=4 sw=4 et:
