#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # add firmware files and licenses
    tar -C / --exclude=lib/firmware/{agere_*,airoha,amd-ucode,amdtee,amlogic,amphion,ar70*,ar9[0-9]*,as102*,\
atusb,av7110,cadence,cavium,cmmb*,cirrus,cis,cpia2,cnm,ct*,cxgb*,cmmb*,cypress,dabusb,dpaa2,dsp56k,dvb*,\
edgeport,emi26,emi62,ess,f2255usb*,go7007,hfi1*,INT*,inside-secure,isdbt*,intel{-ucode,vsc},ixp4xx,keyspan*,\
korg,lgs8g75*,lt9611uxc*,matrox,meson,microchip,moxa,mts*,myri10ge*,myricom,nxp,ositech,phanfw*,powervr,qat*,\
qca,r128,r8a*,rockchip,rp2*,rtl_bt,sb16,s2250*,s5p-*,sdd_*,sms1*,sxg,tdmb*,ttusb-budget,ueagle-atm,usbdux*,\
TAS*,TIAS*,ti,ti-keystone,tlg2300*,tsse_*,v4l*,vicam,vntw*,vxge,wsm_*,wfx,whiteheat*,yam,yamaha,*.txt*,*README*} \
--hard-dereference -cpf - lib/firmware usr/share/licenses/linux-firmware | tar -C "${_ROOTFS}" -xpf -
}

# vim: set ft=sh ts=4 sw=4 et:
