#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! rg -qw 'archboot' /etc/hostname && return
    mv /lib/firmware/regulatory.db /lib/firmware/regulatory.db.p7s /tmp/
    rm -rf /lib/firmware
    mkdir -p /lib/firmware
    mv /tmp/regulatory.db /tmp/regulatory.db.p7s /lib/firmware
}

