#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    tar -C / --exclude=lib/firmware/{[0-9]*-*-0x*,3com,Lontium,advansys,aeonsemi,agere_*,adaptec,airoha,amd{,-ucode,npu,tee},amlogic,amphion,ar3k,ar5523*,ar70*,ar9[0-9]*,arm,as102*,\
ath3k*,atmel,atusb,av7110,bmi260*,bnx2x,cadence,carl*,cavium,cirrus,cis,cpia2,cnm,cs42l43*,ct*,cxgb*,cmmb*,dabusb,dpaa2,dell,dsp56k,dvb*,e100,\
edgeport,emi26,ene-ub6250,f2255usb*,go7007,hfi1*,HP,INT*,intel/{Int*,avs,catpt,dsp*,fw_sst*,ibt*,ice,ipu*,irci*,ish,qat,vpu,vsc},imx,inside-secure,isci,isdbt*,intel{-ucode,},ixp4xx,kaweth,keyspan*,\
lbtf*,LENOVO,lt8713sx*,lt9611uxc*,matrox,meson,microchip,moxa,mrvl/prestera,mts*,myri10ge*,nxp,ositech,phanfw*,powervr,qat*,\
qca,r128,r8a*,rcar_*,realtek,rockchip,rp2*,rtl_bt,rsi*,sb16,s2250*,s5p-*,sdca,sdd_*,slicoss,sms1*,sxg,tdmb*,ueagle-atm,usbdux*,\
tas25*,TAS*,TIAS*,TXNW2781*,tehuti,ti,ti_*,ti-keystone,tlg2300*,tsse_*,v4l*,vntw*,vxge,wsm_*,wfx,whiteheat*,yamaha} \
--hard-dereference -cpf - lib/firmware 2>"${_NO_LOG}" | tar -C "${_ROOTFS}" -xpf - 2>"${_NO_LOG}"
    # add iwlwifi firmware
    tar -C / --hard-dereference -cpf - lib/firmware/intel/iwlwifi 2>"${_NO_LOG}" | tar -C "${_ROOTFS}" -xpf - 2>"${_NO_LOG}"
}
