#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _file /etc/archboot/defaults /usr/lib/archboot/{common.sh,container.sh,login.sh} \
        /usr/bin/archboot-"${_RUNNING_ARCH}"-create-container.sh \
        /usr/share/archboot/patches/pacman-key-aarch64
    _full_dir /usr/lib/archboot/update
    _file_rename /usr/bin/archboot-update.sh /usr/bin/update
    _file /usr/share/archboot/gpg/tpowa.gpg
    # use /etc/profile to launch login.sh
    echo ". /usr/lib/archboot/login.sh" >> "${_ROOTFS}/root/.bashrc"
    # bash completion
     _COMP_DIR="/usr/share/bash-completion/completions"
    _symlink "${_COMP_DIR}/update" "${_COMP_DIR}"/archboot
}
