#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _dir /mnt/install
    _map _binary genfstab arch-chroot pacstrap \
    archboot-{binary-check.sh,not-installed.sh,testsuite.sh} hwdetect
    _file_rename /usr/bin/archboot-setup.sh /usr/bin/setup
    _file_rename /usr/bin/archboot-launcher.sh /usr/bin/launcher
    _file_rename /usr/bin/archboot-quickinst.sh /usr/bin/quickinst
    _file_rename /usr/bin/archboot-localize.sh /usr/bin/localize
    _file_rename /usr/bin/archboot-pacsetup.sh /usr/bin/pacsetup
    _file_rename /usr/bin/archboot-copy-mountpoint.sh /usr/bin/copy-mountpoint.sh
    _file_rename /usr/bin/archboot-rsync-backup.sh /usr/bin/rsync-backup.sh
    _file_rename /usr/bin/archboot-restore-usbstick.sh /usr/bin/restore-usbstick.sh
    _full_dir /usr/lib/archboot/installer
    _file /etc/archboot/defaults
    _file /usr/share/archboot/grub/archboot-background.png
}

# vim: set ft=sh ts=4 sw=4 et:
