#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _file /etc/archboot/defaults /usr/lib/archboot/common.sh \
        /usr/lib/archboot/container.sh /usr/bin/archboot-"$(uname -m)"-create-container.sh \
        /usr/lib/archboot/login.sh /usr/lib/archboot/cpio.sh /usr/bin/archboot-cpio.sh
    _full_dir /usr/lib/archboot/update
    _file /usr/bin/archboot-update.sh /usr/bin/update
    _file /usr/share/archboot/gpg/tpowa.gpg
    # use /etc/profile to launch login.sh
    echo ". /usr/lib/archboot/login.sh" >> "${BUILDROOT}/root/.bashrc"
}

# vim: set ft=sh ts=4 sw=4 et:
