#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # save RAM with deleting already copied content
    rm -rf /var/cache/pacman/pkg
}

# vim: set ft=sh ts=4 sw=4 et:
