#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # add firmware files and licenses
    _map _full_dir "/lib/firmware/amdgpu" "/lib/firmware/i915" "/lib/firmware/nvidia" \
        "/lib/firmware/radeon" "/usr/share/licenses/linux-firmware"
    ### kmx modules
    # AGP and DRM modules for GPUs
    _map _all_modules '/drivers/char/agp/' '/drivers/gpu/drm/'
    # modules that implement the privacy screen interface
    # TODO: Replace with dynamic lookup of modules that depend on the drm_privacy_screen_register symbol
    # See https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/issues/132
    _map _all_modules 'chromeos_privacy_screen?' 'thinkpad_acpi?'
}

# vim: set ft=sh ts=4 sw=4 et:
