#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # add firmware files
    for i in amdgpu i915 nvidia radeon xe; do
        [[ -d "/lib/firmware/${i}" ]] && _full_dir /lib/firmware/${i}
    done
    ### kmx modules
    # AGP and DRM modules for GPUs
    _map _all_mods '/drivers/char/agp/' '/drivers/gpu/drm/'
    # modules that implement the privacy screen interface
    # TODO: Replace with dynamic lookup of modules that depend on the drm_privacy_screen_register symbol
    # See https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/issues/132
    _map _all_mods 'chromeos_privacy_screen' 'thinkpad_acpi'
}

