#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _binary lshw
    _map _file /usr/share/lshw/{manuf,oui,pnpid}.txt
}

# vim: set ft=sh ts=4 sw=4 et:
