#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    for i in cache_{check,dump,metadata_size,repair,restore} \
                   thin_{check,delta,dump,ls,metadata_size,repair,restore,rmap,trim}; do
        _symlink "/usr/bin/${i}" pdata_tools
    done
    _map _binary fsadm lv{change,convert,create,display,extend,reduce,remove,rename,resize,s,scan} \
                 lvm{dump,config,devices,polld,diskscan,sadc,sar,_import_vdo} \
                 pdata_tools pv{change,ck,create,display,move,remove,resize,s,scan} \
                 vg{importclone,importdevices,cfgbackup,cfgrestore,change,ck,convert,\
create,display,export,extend,import,merge,mknodes,reduce,remove,rename,s,scan,split}
    _map _dir /etc/lvm/{backup,archive}
    _map _file /etc/lvm/lvm.conf /usr/lib/{liblvm*,systemd/system/{lvm2*,blk-availability.service,sysinit.target.wants/lvm2*}}
}

# vim: set ft=sh ts=4 sw=4 et:
