#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    local symlink
    ### from thin-provisioning-tools
    _binary pdata_tools
    for symlink in cache_{check,dump,metadata_size,repair,restore} thin_{check,delta,dump,ls,metadata_size,repair,restore,rmap,trim}; do
        _symlink "/usr/bin/${symlink}" pdata_tools
    done
    _map _binary lvmdump lvmconfig vgimportclone fsadm vgcfgbackup vgcfgrestore vgchange \
          vgck vgconvert vgcreate vgdisplay vgexport vgextend vgimport vgmerge vgmknodes \
          vgreduce vgremove vgrename vgs vgscan vgsplit pvchange pvck pvcreate pvdisplay \
          pvmove pvremove pvresize pvs pvscan lvchange lvconvert lvcreate lvdisplay \
          lvextend lvmdiskscan lvmsadc lvmsar lvreduce lvremove lvrename lvresize lvs \
          lvscan lvm_import_vdo lvmdevices lvmpolld vgimportdevices
    _map _dir /etc/lvm/{backup,archive}
    _map _file /usr/lib/liblvm*
    _file /etc/lvm/lvm.conf
}

# vim: set ft=sh ts=4 sw=4 et:
