#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary mdadm mdmon
    _file /etc/mdadm.conf
    _file /usr/share/mdadm/mdcheck
}

