#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! rg -qw 'archboot' /etc/hostname && return
    _install_mods
    rm -r /lib/modules
    _MODS=() _MOD_DEPS=()
}
