#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ### generate motd
    _MOTD="${_ROOTFS}/etc/motd"
    { echo -e "\e[1mWelcome to \e[36mArchboot\e[m\e[1m - Arch Linux ${_RUNNING_ARCH^^}\e[m"
    echo -e "\e[1m----------------------------------------\e[m"
    echo -e "\e[1mVconsole Layout: \e[1;92mPress CTRL+ALT+<F-KEY>\e[m"
    echo -e "-----------------------------------------------------"
    echo -e "| Login     | Network | System | Log      | Systemd |"
    echo -e "| Consoles  | Status  | Status | Messages | Journal |"
    echo -e "|-----------|---------|--------|----------|---------|"
    echo -e "| VC 1 - 3  |  VC 4   |  VC 5  |   VC 8   |  VC 9   |"
    echo -e "|-----------|---------|--------|----------|---------|"
    echo -e "| \e[1;92m  F1-F3\e[m   |   \e[1;92mF4\e[m    |   \e[1;92mF5\e[m   |   \e[1;92mF8\e[m     |   \e[1;92mF9\e[m    |"
    echo -e "-----------------------------------------------------"
if rg -qw net <<< "${_HOOKS[@]}"; then
    echo -e "\e[1mFor Additional Wi-Fi Authentification Or Online Help:\e[m"
    echo -e "  - Use the \e[1;92m'elinks'\e[m web browser and the \e[1;92m'tiny'\e[m IRC"
    echo -e "    client for support on \e[1m#archboot\e[m channel."
fi
if rg -qw installer <<< "${_HOOKS[@]}"; then
    echo -e "\e[1mManage Archboot Environment:\e[m"
    echo -e "  - Use the \e[1;92m'launcher'\e[m or the expert \e[1;92m'update'\e[m script."
    echo -e "\e[1mInstallation:\e[m"
    echo -e "  - Use the \e[1;92m'setup'\e[m or the expert \e[1;92m'quickinst'\e[m script."
fi
    } >> "${_MOTD}"
}
