#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _binary nvim
    _map _full_dir /usr/share/nvim /usr/lib/tree-sitter
    _map _file /usr/share/licenses/neovim/LICENSE.txt
    # add lastplace plugin:
    # https://github.com/neovim/neovim/issues/16339
    _file_rename /usr/share/archboot/nvim/nvim-lastplace.lua /usr/share/nvim/runtime/plugin/nvim-lastplace.lua
}

# vim: set ft=sh ts=4 sw=4 et:
