#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary arping bandwhich bridge clockdiff ctstat dcb dog devlink \
                 elinks ethtool genl ifstat lnstat netscanner nstat miniserve rdma \
                 rtacct rtmon rtstat rustscan ss ssh tc tiny tipc tracepath trip vdpa
    # add iproute 2, add openssl helper libraries
    _map _full_dir /usr/lib/engines-3 /usr/share/tc
    # iptables-nft / nftables
    _map _binary arptables{,-nft,-nft-restore,-nft-save,-restore,-save,-translate} \
                 ebtables{,-nft,-nft-restore,-nft-save,-restore,-save,-translate} \
                 ip{,6}tables{,-apply,-legacy,-legacy-restore,-legacy-save,-nft,-nft-restore,-nft-save,-restore,-restore-translate,-save,-translate} \
                 iptables-xml netshaper nfbpf_compile nfnl_osf nft xtables-{legacy-multi,monitor,nft-multi}
    _map _full_dir /etc/iptables /usr/lib/xtables /usr/share/{iptables,nftables,xtables}
    _map _file /etc/{arptables.conf,ebtables.conf,ethertypes,nftables.conf} /usr/lib/libnetfilter_conntrack*
    # add config for rustmap, no nmap available
    echo "ulimit = 5000" >> "${_ROOTFS}"/root/.rustscan.toml
    echo "scripts = \"None\"" >> "${_ROOTFS}"/root/.rustscan.toml
    # add elinks defaults
    _file_rename /usr/share/archboot/net/etc/elinks/bookmarks /etc/elinks/bookmarks
    _file_rename /usr/share/archboot/net/etc/profile.d/elinks.sh /etc/profile.d/elinks.sh
    # tiny config
    _file_rename /usr/share/archboot/net/usr/share/tiny/config.yml /usr/share/tiny/config.yml
    _symlink /root/.config/tiny/config.yml /usr/share/tiny/config.yml
}

