#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary arping clockdiff tracepath ssh genl \
      ifstat ctstat rtstat lnstat nstat rtacct rtmon ss tc bridge \
      dcb devlink rdma tipc vdpa ethtool elinks weechat brctl
    # add iproute 2, add openssl helper libraries
    _map _full_dir /usr/lib/{tc,engines-3} /usr/share/tc
    # add dnssec-anchors
    _file /etc/trusted-key.key
    # add weechat plugins and defaults
    _map _file /usr/lib/weechat/plugins/{alias,exec,lua,relay,typing,buflist,fifo,irc,xfer,charset,fset,logger,script,trigger}.so
    _file_rename /usr/share/archboot/net/etc/weechat/irc.conf /etc/weechat/irc.conf
    _file_rename /usr/share/archboot/net/etc/weechat/weechat.conf /etc/weechat/weechat.conf
    _file_rename /usr/share/archboot/net/etc/profile.d/weechat.sh /etc/profile.d/weechat.sh
    # add elinks defaults
    _file_rename /usr/share/archboot/net/etc/elinks/bookmarks /etc/elinks/bookmarks
    _file_rename /usr/share/archboot/net/etc/profile.d/elinks.sh /etc/profile.d/elinks.sh
    # fixing licenses
    _map _file /usr/share/licenses/{krb5/LICENSE,openssh/LICENCE,openssl/LICENSE.txt,sqlite/license.txt,dnssec-anchors/LICENSE}
}

# vim: set ft=sh ts=4 sw=4 et:
