#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _all_mods -f '_cs|3com|8390|adaptec|adi|alteon|b44|broadcom/bnx2x|brocade|cadence|cavium|chelsio|cisco|dec|dlink|\
emulex|engleder|hisilicon|huawei|netronome|mellanox|mscc|myricom|natsemi|neterion|nvidia|pensando|qlogic|qualcomm|rdc|\
sfc|silan|sis|smsc|sun|tehuti|vertexcom|via|wiznet' '/drivers/net/ethernet|/net/ipv4|/net/ipv6|/drivers/net/usb'
}

