#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    ! rg -qw 'archboot' /etc/hostname && return
    _install_files
    rm /usr/bin/{arpd,arping,bridge,clockdiff,ctstat,dcb,devlink,\
elinks,ethtool,genl,ifstat,lnstat,nstat,ssh,tracepath,rdma,rtacct,\
rtmon,rtstat,ss,tc,tipc,vdpa}
}

