#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary ip getent ping
    _file_rename /usr/bin/archboot-network.sh /usr/bin/network
    # start dhcpcd on startup
    _file_rename /usr/share/archboot/net/etc/systemd/network/10-wired-auto-dhcp.network \
             /etc/systemd/network/10-wired-auto-dhcp.network
    # ipv6 privacy extensions
    _file_rename /usr/share/archboot/net/etc/systemd/network.conf.d/ipv6-privacy-extensions.conf \
             /etc/systemd/network.conf.d/ipv6-privacy-extensions.conf
}

