#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary exportfs findssl.sh gssproxy nfsstat nfsdcltrack \
                 rpc.{gssd,idmapd,mountd,nfsd,statd} rpcdebug rsync showmount \
                 scp screen sftp sm-notify ssh-{add,agent,copy-id,keygen,keyscan} \
                 sshd start-statd tmux ttyd
    _map _file /etc/{screenrc,ssh/{ssh_config,/moduli},rsyncd.conf,exports,netconfig} \
          /usr/lib/ssh/{sftp-server,ssh-keysign,ssh-pkcs11-helper}
    mkdir -p "${_ROOTFS}"/root/.ssh
    # add ssh key
    if [[ -f /etc/archboot/ssh/archboot-key ]]; then
        _file_rename /etc/archboot/ssh/archboot-key /root/.ssh/archboot-key
        _file /etc/archboot/ssh/archboot-key
    fi
    if [[ -f /etc/archboot/ssh/archboot-key.pub ]]; then
        _file_rename /etc/archboot/ssh/archboot-key.pub /root/.ssh/authorized_keys
        _file_rename /etc/archboot/ssh/archboot-key.pub /root/.ssh/archboot-key.pub
        _file /etc/archboot/ssh/archboot-key.pub
    fi
    # switch port to ARCH and disable password login
    _file_rename /etc/ssh/sshd_config /etc/ssh/sshd_config
    echo "Port 11838" >> "${_ROOTFS}"/etc/ssh/sshd_config
    echo "PasswordAuthentication no" >> "${_ROOTFS}"/etc/ssh/sshd_config
    _full_dir /usr/lib/libnfsidmap
    # fix libldap for /usr/lib/nfsidmap/umich_ldap.so
    _file /usr/lib/libldap.so{,.2}
    _file /usr/lib/liblber.so{,.2}
    _map _dir /var/lib/{nfs/{sm,sm.bak,v4recovery,rpc_pipefs},gssproxy/{clients,rcache}} \
              /var/log/gssproxy
    # mask nfs3 systemd
    for i in rpcbind.service rpcbind.socket rpcbind.target nfs-server.service; do
        _symlink "/etc/systemd/system/${i}" /dev/null
    done
    # systemd tmpfile does not work every time
    _dir /var/empty
    _map _full_dir /etc/{gss,gssproxy}
    # start sshd on startup
    _symlink /etc/systemd/system/multi-user.target.wants/sshd.service /usr/lib/systemd/system/sshd.service
    # start ttyd on startup
    _file /usr/lib/libwebsockets-evlib_uv.so
    _file_rename /usr/share/archboot/remote/usr/bin/remote-login.sh \
                 /usr/bin/remote-login.sh
    _file_rename /usr/share/archboot/remote/etc/systemd/system/ttyd.service \
                 /etc/systemd/system/ttyd.service
    _symlink /etc/systemd/system/multi-user.target.wants/ttyd.service \
             /etc/systemd/system/ttyd.service
}

# vim: set ft=sh ts=4 sw=4 et:
