#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run () {
    # efitools, mokutil, openssl and sbsigntools
    _map _binary mokutil openssl cert-to-efi-{hash-list,sig-list} \
                 efi-{readvar,updatevar} efitool-mkusb flash-var \
                 hash-to-efi-sig-list sig-list-to-certs sign-efi-sig-list \
                 sb{attach,keysync,siglist,sign,varsign,verify}
    _file /etc/ssl/openssl.cnf
    # add mkkeys.sh, 
    # curl -s -L -O https://www.rodsbooks.com/efi-bootloaders/mkkeys.sh
    # modified to use uuidgen instead of python
    _file_rename /usr/bin/archboot-mkkeys.sh /usr/bin/mkkeys.sh
    if [[ "${_RUNNING_ARCH}" == "x86_64" ]]; then
        _map _file /usr/share/archboot/bootloader/{shimx64.efi,mmx64.efi,mmia32.efi,shimia32.efi}
    fi
    if [[ "${_RUNNING_ARCH}" == "aarch64" ]]; then
        _map _file /usr/share/archboot/bootloader/{mmaa64.efi,shimaa64.efi}
    fi
    # add generate keys script
    _file_rename /usr/bin/archboot-secureboot-keys.sh /usr/bin/secureboot-keys.sh
}

