#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _map _binary smartctl smartd update-smart-drivedb
    _map _file /etc/{conf.d/smartd,smartd.conf}
}

