#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _full_dir /usr/share/kbd
    #add kbd binaries
    _map _binary dumpkeys kbd_mode chvt deallocvt fgconsole getkeycodes kbdinfo \
                 kbdrate loadunimap mapscrn openvt psfaddtable psfgettable psfstriptable \
                 psfxtable setkeycodes setleds setmetamode setvtrgb showconsolefont \
                 showkey unicode_start unicode_stop vlock
    # only add resizecons on x86_64 
    [[ "${_RUNNING_ARCH}" == "x86_64" ]] && _binary resizecons
    # add fbset
    _binary fbset
    _file /etc/fb.modes
}

