#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _all_mods -f '_cs|b43' '/net/wireless/|/net/ieee80211/|/net/mac80211/'
    if [[ "${_RUNNING_ARCH}" == "x86_64" ]]; then
        # add broadcom wl support
        _mod wl
        _file /usr/lib/modprobe.d/broadcom-wl.conf
    fi
}

# vim: set ft=sh ts=4 sw=4 et:
