#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    # start iwd service
    _symlink /etc/systemd/system/multi-user.target.wants/iwd.service /usr/lib/systemd/system/iwd.service
    _map _binary hwsim iw{,ctl,mon} rfkill set-wireless-regdom
    # add iwd and ead daemon
    _map _binary /usr/lib/iwd/{iwd,ead}
    # add hwsim helper script
    _binary archboot-hwsim.sh
    # crda support
    _map _file /etc/conf.d/wireless-regdom /usr/lib/crda/{regulatory.bin,pubkeys/wens.key.pub.pem}
    # disable powersave by default on wifi devices
    _file_rename /usr/share/archboot/wireless/etc/udev/rules.d/60-wifi-disable-powersave.rules \
            /etc/udev/rules.d/60-wifi-disable-powersave.rules
}

