#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-3.0-or-later
# Created by Tobias Powalowski <tpowa@archlinux.org>

_run ()
{
    _all_mods -f '_cs|admtek|atmel|b43|intersil|ipw2x00|iwlegacy|microchip|purelifi|quantenna|rsi|silabs|/st/|zydas' \
                 '/net/wireless/|/net/ieee80211/|/net/mac80211/'
}

