#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/vim"
    add_file "/usr/share/vim/vim73/syntax/syntax.vim"
    add_file "/usr/share/vim/vim73/syntax/conf.vim"
    add_file "/usr/share/vim/vim73/syntax/sh.vim"
    add_file "/usr/share/vim/vim73/syntax/grub.vim"
    add_file "/usr/share/vim/vim73/syntax/lilo.vim"
    add_file "/usr/share/vim/vim73/syntax/manual.vim"
    add_file "/usr/share/vim/vim73/syntax/synload.vim"
    add_file "/usr/share/vim/vim73/syntax/colortest.vim"
    add_file "/usr/share/vim/vim73/syntax/syncolor.vim"
    add_file "/usr/share/vim/vim73/syntax/hitest.vim"
    add_file "/usr/share/vim/vim73/syntax/whitespace.vim"
    add_file "/usr/share/vim/vim73/syntax/modconf.vim"
    add_file "/usr/share/vim/vim73/syntax/resolv.vim"
    add_file "/usr/share/vim/vim73/syntax/fstab.vim"
    add_file "/usr/share/vim/vim73/filetype.vim"
}

help ()
{
cat<<HELPEOF
  This hook includes small version of vim on an arch boot image.
HELPEOF
} 
