#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "weechat-curses"
    add_full_dir "/usr/lib/weechat"
}

help ()
{
cat<<HELPEOF
  This hook includes weechat on an arch boot image.
HELPEOF
} 
