#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    DEPENDS="systemd-sysvcompat wget bash coreutils cryptsetup dialog \
             e2fsprogs findutils gawk grep iputils jfsutils less lvm2 mdadm kmod nano \
             ncurses net-tools gnu-netcat pcmciautils procps-ng psmisc reiserfsprogs sed snarf \
             tar util-linux which wireless_tools xfsprogs dnsutils hdparm memtest86+ \
             inetutils openssh hwdetect shadow bridge-utils ifenslave cpupower links \
             dosfstools filesystem linux glibc linux-api-headers \
             links pacman pacman-mirrorlist screen kbd pam dhcpcd bzip2 gcc-libs openssl zlib \
             elfutils gpm sysfsutils libgcrypt libgpg-error popt kexec-tools ppp libpcap rp-pppoe \
             iptables ntfs-3g isdn4k-utils pciutils usbutils vpnc openvpn b43-fwcutter \
             wpa_supplicant gzip rsync libarchive device-mapper cracklib nfs-utils nfsidmap \
             readline acl attr pcre cpio archboot fuse libusb-compat libusb vim vim-runtime \
             lzo2 libsasl libldap libevent gpm sdparm pptpclient licenses zd1211-firmware cifs-utils dmraid \
             linux-atm netctl openresolv parted tzdata ntp iw crda wireless-regdb libnl iproute2 dhclient \
             syslinux mtools perl gmp krb5 sqlite db dbus libcap fsarchiver xz librpcsecgss \
             libtirpc wipe ddrescue testdisk ifplugd libdaemon wpa_actiond rfkill libgssglue icu gptfdisk \
             btrfs-progs nilfs-utils linux-firmware ipw2100-fw ipw2200-fw iana-etc chntpw \
             grub gummiboot refind-efi efivar efibootmgr lockdown-ms prebootloader file keyutils \
             yp-tools curl smartmontools dnsmasq lftp openconnect libxml2 libproxy speedtouch tcpdump nmap lua \
             weechat gnutls nettle libtasn1 rpcbind expat progsreiserfs glib2 freetype2 libssh2 libedit \
             talloc eventlog idnkit libjpeg-turbo pth gnupg libksba libassuan pinentry dirmngr gpgme ldns \
             dnssec-anchors hwids systemd dmidecode archlinux-keyring haveged \
             pambase traceroute arch-wiki-lite intel-ucode arch-install-scripts zsh gdbm \
             grml-zsh-config sysvinit-tools xl2tpd wvdial usb_modeswitch f2fs-tools"
    
    for i in $DEPENDS; do
	for k in  $(echo /var/lib/pacman/local/$i-[0-9]*-[0-9]*); do
		[ -e "$k/install" ] && add_file "$k/install"
		add_file "$k/files"
		add_file "$k/desc"
	done
    done
}

help ()
{
cat<<HELPEOF
  This hook includes the pacman depends on an arch boot image.
HELPEOF
}
