#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_all_modules 'arch/x86/kernel/cpu/cpufreq|drivers/cpufreq'
    map add_binary "cpupower" "cpufreq-bench_plot.sh"
    add_file "/etc/cpufreq-bench.conf"
}

help ()
{
cat<<HELPEOF
  This hook includes cpupower tools on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
