#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    for i in $(find /usr/share/licenses/common ! -type d -type f); do
        add_file $i
    done
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook includes the common licenses on an arch boot image.
HELPEOF
} 