#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    # add firmware files and licenses
    for i in $(pacman -Ql linux-firmware | cut -d ' ' -f2 | grep -v /$); do
        add_file "$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook includes linux_firmware on an arch boot image.
HELPEOF
}
