#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "wvdial"
    add_binary "wvdialconf"
    # add license
    add_file "/usr/share/licenses/wvdial/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes wvdial on an arch boot image.
HELPEOF
} 
