#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules -f 'wireless' '/drivers/net/'
    # add staging modules
    STAGING="et131x"
    for i in $STAGING; do
        add_checked_modules "/drivers/staging/$i"
    done
    apps="/bin/dnsdomainname /usr/bin/domainname /bin/netstat /usr/bin/nisdomainname /usr/bin/ypdomainname \
          /sbin/arp /sbin/ipmaddr /sbin/iptunnel /sbin/mii-tool /sbin/nameif /sbin/plipconfig /sbin/rarp \
	  /sbin/slattach /usr/bin/traceroute /usr/sbin/arping /usr/sbin/clockdiff \
	  /usr/sbin/rarpd /usr/sbin/rdisc /usr/sbin/tftpd /usr/sbin/tracepath /usr/sbin/tracepath6 /sbin/route \
	  /usr/bin/telnet /usr/bin/ssh /usr/sbin/arpd \
	  /usr/sbin/genl /usr/sbin/ifstat /usr/sbin/lnstat /usr/sbin/nstat /usr/sbin/rtacct \
	  /usr/sbin/rtmon  /usr/sbin/ss /usr/sbin/tc /usr/sbin/dhclient /usr/bin/ifplugd \
	  /usr/bin/ifplugstatus /sbin/ip /usr/bin/ping /usr/bin/ping6"
    for i in $apps; do
        add_binary "$i"
    done
    appfiles="/usr/sbin/ifcfg /usr/sbin/routef /usr/sbin/routel /usr/sbin/rtpr /sbin/dhcpcd /sbin/ifenslave /usr/sbin/brctl"
    for i in $appfiles; do
        add_file "$i"
    done
    symlinks="/usr/sbin/ctstat /usr/sbin/rtstat"
    for i in $symlinks; do
        add_binary "$(which $(basename $(readlink "$i")))"
        add_symlink "$i" "$(which $(basename $(readlink "$i")))"
    done
    for i in $(find /usr/lib/dhcpcd -type f); do
        add_file "$i"
    done
    add_file "/etc/dhcpcd.conf"
    add_dir "/var/lib/dhcpcd"
    add_full_dir "/usr/lib/tc"
    add_full_dir "/usr/share/tc"
    add_full_dir "/etc/iproute2"
    # add dnssec-anchors
    add_file "/etc/trusted-key.key"
    # add dhclient support
    add_file "/sbin/dhclient-script"
    add_dir "/var/lib/dhclient"
    add_dir "/var/state/dhcp"
    # add ifplugd support
    add_full_dir "/etc/ifplugd"
    # fixing licenses
    add_file "/usr/share/licenses/db/LICENSE"
    add_file "/usr/share/licenses/dhcpcd/LICENSE"
    add_file "/usr/share/licenses/dhclient/LICENSE"
    add_file "/usr/share/licenses/krb5/LICENSE"
    add_file "/usr/share/licenses/openssh/LICENCE"
    add_file "/usr/share/licenses/openssl/LICENSE"
    add_file "/usr/share/licenses/sqlite/license.txt"
    add_file "/usr/share/licenses/dnssec-anchors/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the network on an arch boot image.
HELPEOF
}
