#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/modem_run /usr/bin/pppoa2 /usr/bin/pppoa3"
    for i in $apps; do
        add_binary "$i"
    done
    add_dir "/etc/speedtouch/"
    add_file "/usr/bin/speedtouch-setup"
    add_file "/usr/bin/speedtouch-start"
    add_file "/usr/bin/speedtouch-stop"
    add_file "/usr/share/speedtouch/boot.v123.bin"
}

help ()
{
cat<<HELPEOF
  This hook includes speedtouch on an arch boot image.
HELPEOF
} 
