#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    [ "${RUNPROGRAM}"  = "mkisolinux" ] && cp "/boot/amd-ucode.img" "${TEMPDIR}/boot/amd-ucode.img"
    [ "${RUNPROGRAM}"  = "archboot-tarball-helper.sh" ] && cp "/boot/amd-ucode.img" "${TEMPDIR}/boot/amd-ucode.img"
    [ "${RUNPROGRAM}"  = "mksyslinux" ] && cp "/boot/amd-ucode.img" "${TEMPDIR}/boot/amd-ucode.img"
    [ "${RUNPROGRAM}"  = "mkpxelinux" ] && cp "/boot/amd-ucode.img" "${INSTALLDIR}/amd-ucode.img"
    # fix license files
    add_file "/usr/share/licenses/amd-ucode/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes amd-ucode on an arch boot image.
HELPEOF
} 
