#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="dnsdomainname netstat arp ipmaddr iptunnel mii-tool nameif plipconfig rarp \
	  slattach traceroute arping clockdiff rarpd rdisc tracepath \
	  dig host nslookup telnet ssh arpd genl ifstat ctstat rtstat lnstat nstat rtacct rtmon ss \
	  tc dhclient ifplugd ifplugstatus bridge dcb devlink rdma tipc vdpa \
	  ping ethtool elinks dhcp_lease_time dhcp_release dhcp_release6 \
	  routel brctl dhclient-script"
    for i in $apps; do
        add_binary "$i"
        rm /usr/bin/"$i"
    done
    # add iproute 2, add openssl helper libraries
    map add_full_dir "/usr/lib/tc" "/usr/share/tc" "/etc/iproute2" "/usr/lib/engines"
    # add dnssec-anchors
    add_file "/etc/trusted-key.key"
    # add dhclient support
    map add_dir "/var/lib/dhclient" "/var/state/dhcp"
    # add ifplugd support
    add_full_dir "/etc/ifplugd"
    # fixing licenses
    map add_file "/usr/share/licenses/db/LICENSE" "/usr/share/licenses/dhclient/LICENSE" \
        "/usr/share/licenses/bind/LICENSE" "/usr/share/licenses/krb5/LICENSE" \
        "/usr/share/licenses/openssh/LICENCE" "/usr/share/licenses/openssl/LICENSE" \
        "/usr/share/licenses/sqlite/license.txt" "/usr/share/licenses/dnssec-anchors/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the network on update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
