#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "dumpkeys"
    add_binary "kbd_mode"
        for i in $(find /usr/share/kbd/ ! -type d ! -name "mac*"  ! -name "ppc" ! -name "ppc" ! -name "atari*" ! -name "sun*" ! -name "README*" ! -name "amiga*"); do
            add_file $i
        done
    add_file /usr/share/archboot/keymap/km /usr/bin/km
}

help ()
{
cat<<HELPEOF
  This hook includes the keymaps and fonts on an arch boot image.
HELPEOF
}
