#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/netcfg-wpa_actiond /usr/bin/netcfg-wpa_actiond-action /usr/bin/netcfg-menu \
          /usr/bin/netcfg-daemon /usr/bin/wifi-menu /usr/bin/netcfg"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/usr/lib/network/"
    add_full_dir "/etc/network.d/examples"
    add_dir "/etc/network.d/hooks"
    add_file "/etc/rc.d/net-profiles"
    add_file "/etc/rc.d/net-rename"
    add_file "/etc/rc.d/net-auto-wired"
    add_file "/etc/rc.d/net-auto-wireless"
    add_file "/etc/rc.d/functions.d/net-set-variable"
    add_file "/etc/iftab"
    add_file "/etc/ifplugd/netcfg.action"
    add_file "etc/conf.d/netcfg"
    # fix licenses
    add_file "/usr/share/licenses/netcfg/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the netcfg package on an arch boot image.
HELPEOF
}
