#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    # add firmware files and licenses
    map add_full_dir "/lib/firmware" "/usr/share/licenses/linux-firmware"
    # remove not used firmware
    rm -rf ${BUILDROOT}/lib/firmware/{amphion,as102*,atusb,av7110,cavium,cmmb*,cis,cpia2,cnm,ct*,cxgb*,cmmb*,dabusb,dpaa2,dsp56k,dvb*,edgeport,emi26,emi62,ess,f2255usb*,go7007,hfi1*,isdbt*,keyspan*,korg,meson,moxa,mts*,myri10ge*,myricom,nxp,ositech,sb16,s2250*,s5p-*,sms1*,rtl_bt,tdmb*,ttusb-budget,ueagle-atm,usbdux*,ti,ti-keystone,v4l*,vicam,vxge,whiteheat*,yamaha}
    find ${BUILDROOT}/lib/firmware -type f -name "*txt*" -exec rm {} \;
    find ${BUILDROOT}/lib/firmware -type f -name "*README*" -exec rm {} \;
}

help ()
{
cat<<HELPEOF
  This hook includes linux-firmware on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
