#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/sbin/pptp"
    add_full_dir "/etc/ppp"
}

help ()
{
cat<<HELPEOF
  This hook includes pptpclient on an arch boot image.
HELPEOF
} 
