#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary genfstab arch-chroot pacstrap \
          archboot-$(uname -m)-release.sh \
          archboot-restore-usbstick.sh isoinfo archboot-copy-mountpoint.sh \
          archboot-rsync-backup.sh archboot-binary-check.sh
    add_file "/usr/bin/archboot-setup.sh" "/usr/bin/setup"
    add_file "/usr/bin/archboot-quickinst.sh" "/usr/bin/quickinst"
    # include cachedir on booted archboot or container
    add_full_dir "/var/cache/pacman/pkg"
    # save RAM with deleting already copied content
    [[ -d "/var/cache/pacman/pkg" ]] && rm -r "/var/cache/pacman/pkg"
}

help ()
{
cat<<HELPEOF
  This hook includes the archboot installer,archinstaller and arch-install-scripts 
  on update installer routine.
  DO NOT USE ON REGULAR SYSTEM!
HELPEOF
}
