#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    ### adding passwd file for correct shell
    add_file "/usr/share/archboot/installer_latest/etc/passwd" "/etc/passwd"
}

help ()
{
cat <<HELPEOF
  This hook sets up stripped down base for for latest image.
HELPEOF
}
