#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/sbin/hwclock"
    add_binary "/bin/date /usr/bin/ntpdate"
    for i in $(find /usr/share/zoneinfo ! -type d); do
        add_file $i
    done
    add_file "/usr/share/archboot/tz/tz" "/usr/bin/tz"
    # fix licenses
    add_file "/usr/share/licenses/ntp/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the timezone data on an arch boot image.
HELPEOF
}
