#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "testdisk"
    add_binary "photorec"
}

help ()
{
cat<<HELPEOF
  This hook includes testdisk on an arch boot image.
HELPEOF
} 
