#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/mmc/'
}

help ()
{
cat<<HELPEOF
  This hook adds the necessary modules for a mmc device.
HELPEOF
}
 
