#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary wvdial wvdialconf
    # add license
    add_file "/usr/share/licenses/wvdial/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes wvdial on an archboot image.
HELPEOF
} 
