#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "mdassemble"
    add_binary "mdmon"
    # add custom archboot mdadm.conf to avoid mdadm handling isw and ddf metadata devices
    # which are also covered by dmraid
    add_file "/usr/share/archboot/mdadm/etc/mdadm.conf" "/etc/mdadm.conf"
}

help ()
{
cat<<HELPEOF
  This hook adds complete mdadm to arch boot image
  which is not covered by mdadm_udev hook.
HELPEOF
}
