#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/firewire/|firewire-sbp2|sr_mod|sd_mod'
}

help ()
{
cat<<HELPEOF
  This hook loads the necessary modules for a firewire root device.
  Detection will take place at runtime. To minimize the modules
  in the image, add the autodetect hook too.
HELPEOF
}
 
