#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/poff /usr/bin/pon /usr/sbin/chat /usr/sbin/plog /usr/sbin/pppd /usr/sbin/pppdump \
          /usr/sbin/pppoe-discovery /usr/sbin/pppstats"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/usr/lib/pppd"
    add_full_dir "/etc/ppp"
    # fix license files
    add_file "/usr/share/licenses/libpcap/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes ppp on an arch boot image.
HELPEOF
} 
