#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "ddrescue"
}

help ()
{
cat<<HELPEOF
  This hook includes ddrescue on an archboot image.
HELPEOF
} 
