#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/sbin/pppoe /usr/sbin/pppoe-connect /usr/sbin/pppoe-relay /usr/sbin/pppoe-server \
          /usr/sbin/pppoe-setup /usr/sbin/pppoe-sniff /usr/sbin/pppoe-start /usr/sbin/pppoe-status \
	  /usr/sbin/pppoe-stop"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/usr/lib/rp-pppoe"
    add_full_dir "/etc/ppp"
    add_file "/etc/rc.d/adsl"
}

help ()
{
cat<<HELPEOF
  This hook includes rp-pppoe on an arch boot image.
HELPEOF
} 
