#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_module "pcspkr"
}

help ()
{
cat<<HELPEOF
  This hook includes the pcspkr on an arch boot image.
HELPEOF
}
