#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/*virtio*'
}

help ()
{
cat<<HELPEOF
  This hook includes virtio modules on an arch boot image.
HELPEOF
} 
