#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_full_dir "/usr/share/kbd"
    #add kbd binaries
    map add_binary dumpkeys kbd_mode chvt deallocvt fgconsole getkeycodes kbdinfo kbdrate loadunimap mapscrn openvt psfaddtable psfgettable psfstriptable psfxtable setkeycodes setleds setmetamode setvtrgb showconsolefont showkey unicode_start unicode_stop vlock
    # only add resizecons on x86_64 
    [[ "$(uname -m)" == "x86_64" ]] && add_binary resizecons
    # add fbset
    add_binary fbset
    add_file /etc/fb.modes
    # add terminus-font
    map add_full_dir /usr/share/fonts /usr/share/fontconfig
    add_file /usr/share/licenses/terminus-font/LICENSE
}

help ()
{
cat<<HELPEOF
  This hook includes the vconsole keymaps and fonts on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
