#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary lspci setpci update-pciids
    add_file "/usr/share/hwdata/pci.ids"
}

help ()
{
cat<<HELPEOF
  This hook includes pciutils on an archboot image.
HELPEOF
} 
