#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    [ "${RUNPROGRAM}"  = "mkisolinux" ] && cp "/boot/intel-ucode.img" "${TEMPDIR}/boot/intel-ucode.img"
    [ "${RUNPROGRAM}"  = "archboot-tarball-helper.sh" ] && cp "/boot/intel-ucode.img" "${TEMPDIR}/boot/intel-ucode.img"
    [ "${RUNPROGRAM}"  = "mksyslinux" ] && cp "/boot/intel-ucode.img" "${TEMPDIR}/boot/intel-ucode.img"
    [ "${RUNPROGRAM}"  = "mkpxelinux" ] && cp "/boot/intel-ucode.img" "${INSTALLDIR}/intel-ucode.img"
    # fix license files
    add_file "/usr/share/licenses/intel-ucode/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes intel-ucode on an arch boot image.
HELPEOF
} 
