#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    cp "/boot/amd-ucode.img" "${TEMPDIR}/boot/amd-ucode.img"
    # fix license files
    add_file "/usr/share/licenses/amd-ucode/LICENSE.amd-ucode"
}

help ()
{
cat<<HELPEOF
  This hook includes amd-ucode on an archboot image.
HELPEOF
} 
