#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/tcpdump"
    add_file "/usr/share/licenses/tcpdump/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes tcpdump on an arch boot image.
HELPEOF
} 
