#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary nmap ncat nping
    add_full_dir "/usr/share/nmap"
    add_file "/usr/share/licenses/nmap/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes nmap on an archboot image.
HELPEOF
} 
