#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/sbin/udevadm"
    add_runscript
}

help ()
{
cat <<HELPEOF
  This hook will trigger your udev events.
HELPEOF
}
