#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "efibootmgr"
}

help ()
{
cat<<HELPEOF
  This hook includes efibootmgr on an archboot image.
HELPEOF
}

