#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary testdisk photorec
}

help ()
{
cat<<HELPEOF
  This hook includes testdisk on an archboot image.
HELPEOF
} 
