#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    addbinary "/usr/bin/ddrescue"
}

help ()
{
cat<<HELPEOF
  This hook includes ddrescue on an arch boot image.
HELPEOF
} 
