#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary lspci setpci update-pciids
}

help ()
{
cat<<HELPEOF
  This hook includes pciutils on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
