#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/acpi/'
}

help ()
{
cat<<HELPEOF
  This hook includes the acpi subsystem on an arch boot image.
HELPEOF
}
