#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "vim"
    add_file "/etc/vimrc"
    # fix vi symlink
    add_symlink "/usr/bin/vi" "/usr/bin/vim"
    add_file "/usr/share/vim/vimfiles/archlinux.vim"
    add_file "/usr/share/vim/vim82/defaults.vim"
    SYNTAX=(syntax conf sh grup manual synload colortest syncolor hitest whitespace modconf resolv fstab bash zsh exports passwd sysctl systemd vim)
    for i in ${SYNTAX}; do
        add_file "/usr/share/vim/vim82/syntax/$i.vim"
    done
    add_file "/usr/share/vim/vim82/filetype.vim"
    add_file "/usr/share/vim/vim82/rgb.txt"
    add_file "/usr/share/licenses/vim/license.txt"
}

help ()
{
cat<<HELPEOF
  This hook includes small version of vim on an arch boot image.
HELPEOF
} 
