#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/sbin/openconnect"
}

help ()
{
cat<<HELPEOF
  This hook includes openconnect on an arch boot image.
HELPEOF
} 
