#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/sbin/lspci" 
    add_binary "/usr/sbin/setpci"
    add_file "/usr/share/hwdata/pci.ids"
}

help ()
{
cat<<HELPEOF
  This hook includes pciutils on an arch boot image.
HELPEOF
} 
