#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_file "/usr/bin/hwdetect"
}

help ()
{
cat <<HELPEOF
  This hook will add hwdetect on an arch boot image.
HELPEOF
}
