#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary usb_modeswitch usb_modeswitch_dispatcher tclsh
    map add_full_dir "/usr/lib/tcl8" "/usr/lib/tcl8.6"
    map add_file "/etc/usb_modeswitch.conf" "/etc/usb_modeswitch.setup"
    map add_full_dir "/etc/usb_modeswitch.d" "/usr/share/usb_modeswitch"
    add_dir "/var/lib/usb_modeswitch"
}

help ()
{
cat<<HELPEOF
  This hook includes usb_modeswitch on an archboot image.
HELPEOF
} 
