#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/hv/hv_*'
}

help ()
{
cat<<HELPEOF
  This hook includes hypervisor modules on an arch boot image.
HELPEOF
} 
