#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/firmware/dmi-sysfs'
    add_binary "/usr/bin/dmidecode"
    add_binary "/usr/bin/biosdecode"
}

help ()
{
cat<<HELPEOF
  This hook includes dmidecode on an arch boot image.
HELPEOF
}

