#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="hwclock date ntpdate ntpd ntp-keygen ntp-wait ntpdc ntpq \
          ntptime ntptrace tzselect"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/ntp.conf"
    for i in $(find /usr/share/zoneinfo ! -type d); do
        add_file "$i"
    done
    add_dir "/var/lib/ntp"
    chown ntp:root "$BUILDROOT/var/lib/ntp"
    add_file "/usr/bin/archboot-tz.sh" "/usr/bin/tz"
    # fix licenses
    add_file "/usr/share/licenses/ntp/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the timezone data on an archboot image.
HELPEOF
}
