#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="pcf2vpnc vpnc vpnc-disconnect"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/vpnc/default.conf"
    add_file "/etc/vpnc/vpnc-script"

}

help ()
{
cat<<HELPEOF
  This hook includes vpnc on an archboot image.
HELPEOF
} 
