#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_all_modules 'md/dm-*'
    map add_binary dmsetup dmeventd blkdeactivate dmstats
    add_dir "/dev/mapper"
    add_full_dir "/usr/lib/device-mapper"
    for i in /usr/lib/libdevmapper*; do
        add_file "$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook includes devicemapper on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
