#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/isdn/'
    apps="/usr/sbin/hisaxctrl /usr/sbin/icnctrl /usr/sbin/imon /usr/sbin/imontty /usr/sbin/ipppd \
          /usr/sbin/ipppstats /usr/sbin/isdnctrl /usr/sbin/isdnlog /usr/sbin/mkzonedb /usr/bin/isdnconf \
	  /usr/bin/isdnrate /usr/bin/isdnrep /usr/bin/capiinfo /usr/sbin/rcapid /usr/sbin/capiinit \
	  /usr/sbin/avmcapictrl"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/isdn/callerid.conf"
    add_file "/etc/isdn/isdn.conf"
    add_file "/etc/isdn/isdnlog.isdnctrl0.options"
    add_file "/etc/isdn/isdnlog.users"
    add_file "/etc/isdn/rate.conf"
    add_file "/etc/isdn/stop"
}

help ()
{
cat<<HELPEOF
  This hook includes the isdn subsystem on an arch boot image.
HELPEOF
}
