#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    if [[ "$(uname -m )" == "x86_64" ]]; then
        add_file "/usr/share/refind/refind_x64.efi"
        add_full_dir "/usr/share/refind/drivers_x64"
        add_full_dir "/usr/share/refind/tools_x64"
    fi
    
    if [[ "$(uname -m )" == "i686" ]]; then
        add_file "/usr/share/refind/refind_ia32.efi"
        add_full_dir "/usr/share/refind/drivers_ia32"
        add_full_dir "/usr/share/refind/tools_ia32"
    fi
    
    add_full_dir "/usr/share/refind/keys"
    add_file "/usr/share/refind/refind.conf-sample"
    
    appfiles="/usr/bin/refind-install /usr/bin/refind-mkfont /usr/bin/refind-mkrlconf /usr/bin/refind-mvrefind"
    for i in $appfiles; do
        add_file "$i"
    done
    
    
}

help ()
{
cat<<HELPEOF
  This hook includes refind-efi on an arch boot image.
HELPEOF
}

