#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "hwclock"
    add_binary "date"
    add_binary "ntpdate"
    add_binary "ntpd"
    add_file "/etc/ntp.conf"
    for i in $(find /usr/share/zoneinfo ! -type d); do
        add_file $i
    done
    add_dir "/var/lib/ntp"
    chown ntp:root "$BUILDROOT/var/lib/ntp"
    add_file "/usr/bin/archboot-tz.sh" "/usr/bin/tz"
    # fix licenses
    add_file "/usr/share/licenses/ntp/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the timezone data on an archboot image.
HELPEOF
}
