#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="syslinux extlinux mtools"
    for i in $apps; do
        add_binary "$i"
    done
    symlinks="/usr/bin/mcopy /usr/bin/mattrib"
    for i in $symlinks; do
        add_binary "$(which $(basename $(readlink "$i")))"
        add_symlink "$i" "$(which $(basename $(readlink "$i")))"
    done
    for i in /usr/lib/syslinux/*; do
        [ -f $i ] && add_file "$i"
    done
    add_file "/usr/lib/gconv/gconv-modules"
    add_file "/usr/lib/gconv/IBM850.so"
}

help ()
{
cat<<HELPEOF
  This hook includes syslinux on an arch boot image.
HELPEOF
} 
