#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    ### add pcspkr
    add_module "pcspkr"
    ### add init modules
    map add_module virtio? zram? btrfs? zstd? libcrc32c?
    ### keyboard modules
    add_all_modules -f '(_cs|sl811_hcd|isp116x_hcd)' '/usb/host'
    add_all_modules '/hid/hid'
    add_module 'usbhid'
    add_all_modules '/input/(serio|keyboard)'
    ### kmx modules
    # AGP and DRM modules for GPUs
    map add_all_modules '/drivers/char/agp/' '/drivers/gpu/drm/'
    # modules that implement the privacy screen interface
    # TODO: Replace with dynamic lookup of modules that depend on the drm_privacy_screen_register symbol
    # See https://gitlab.archlinux.org/archlinux/mkinitcpio/mkinitcpio/-/issues/132
    map add_all_modules 'chromeos_privacy_screen?' 'thinkpad_acpi?'
}

help ()
{
cat <<HELPEOF
  This hook includes init, keyboard, kms and pcspkr support
  for an archboot image.
  DO NOT remove this one unless you know what you're doing.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
