#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    # add staging wireless here
    STAGING="rtl8188eu rtl8192e rtl8192u rtl8712 rtl8723bs vt6655 vt6656 wlan-ng"
    for i in $STAGING; do
        add_checked_modules "/drivers/staging/$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook includes staging wireless on an archboot image.
HELPEOF
}
