#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_file "/usr/bin/hwdetect"
}

help ()
{
cat <<HELPEOF
  This hook will use hwdetect to load 
  and detect the needed modules for your system.
HELPEOF
}
