#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="getent head id cksum tail test tr uptime w who which whoami xargs \
          swapon uniq seq snarf fdisk sfdisk cfdisk parted free less \
          chgrp dialog dmesg egrep fgrep stty sync tar bsdcpio hdparm \
          chroot dirname expr bunzip2 bzcat bzip2 su cpio sdparm tput \
          ifconfig losetup mkfifo mknod  lzmadec lzop lzma lzcat unlzma unxz xzcat \
          lastb last wall mesg utmpdump xzdec switch_root pivot_root chcpu ctrlaltdel \
          gdisk sgdisk cgdisk fixparts findmnt lsblk swaplabel cal chrt col colcrt \
          colrm column fallocate flock getopt ionice ipcmk ipcrm ipcs isosize swapoff \
          look lsfd lscpu mcookie namei prlimit rename renice rev script scriptreplay uname26 \
          linux32 linux64 setarch setsid setterm taskset ul unshare uuidgen whereis write \
          addpart delpart ldattach partx readprofile rtcwake uuidd sysctl pkill pmap \
          pwdx slabtop tload vmstat watch file eject keyctl request-key zsh hostname tac \
          sulogin resizepart lslocks wdctl zless zgrep fold od shred blockdev blkdiscard \
          newgrp nsenter runuser vigr vipw diff lsmod lzcmp lzdiff lzegrep \
          lzgrep lzfgrep xzegrep xzfgrep xzgrep lzless lzmore  nc reset blkzone \
          chmem choom fincore hardlink irqtop lsipc lsirq lslogins lsmem lsns mkfs scriptlive \
          setpriv uclampset uuidparse zramctl [ b2sum base32 base64 basenc chcon comm csplit \
          dircolors expand factor fmt hostid join link logname md5sum nice nl nohup \
          nproc numfmt paste pathchk pinky pr printenv ptx runcon sha1sum sha224sum \
          sha256sum sha384sum sha512sum shuf split stdbuf sum timeout truncate tsort \
          unexpand unlink users vdir pwait fuser peekfd prtstat pslog pstree newgidmap newuidmap \
          lzmainfo xzcmp gzexe uncompress zcmp zdiff zegrep zfgrep zforce zmore znew \
          bzdiff bzgrep bzip2recover bzmore chacl getfacl setfacl attr getfattr \
          setfattr pzstd unzstd zstdcat zstdgrep zstdless zstdmt lz4 lz4c lz4cat unlz4 gunzip zcat"
    if [[ "$(uname -m)" == "x86_64" ]]; then
        apps="i386 x86_64 $apps"
    fi
    for i in $apps; do
        rm /usr/bin/"$i"
    done
}

help ()
{
cat <<HELPEOF
  This hook cleans up binaries of archboot_base,
  for a update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
