#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules -f 'nfp' -f 'liquidio' -f 'mellanox' -f 'wireless' -f 'bnx2x' -f 'bna' -f 'softing_cs' -f 'qed' '/drivers/net/'
    map add_binary ip getent ping wget
    # start dhcpcd on startup
    add_symlink "/etc/systemd/system/multi-user.target.wants/systemd-networkd.service" "/usr/lib/systemd/system/systemd-networkd.service"
    add_symlink "/etc/systemd/system/multi-user.target.wants/systemd-resolved.service" "/usr/lib/systemd/system/systemd-resolved.service"
    add_file "/usr/share/archboot/net/etc/systemd/network/10-wired-auto-dhcp.network" "/etc/systemd/network/10-wired-auto-dhcp.network"
    add_file /etc/wgetrc
}

help ()
{
cat<<HELPEOF
  This hook includes the basic network on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
