#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary pcf2vpnc vpnc vpnc-disconnect
    map add_file "/etc/vpnc/default.conf" "/etc/vpnc/vpnc-script"
}

help ()
{
cat<<HELPEOF
  This hook includes vpnc on an archboot image.
HELPEOF
} 
