#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules 'arch/x86/kernel/cpu/cpufreq|drivers/cpufreq'
    map add_binary "cpupower" "cpufreq-bench_plot.sh"
    add_file "/etc/cpufreq-bench.conf"
}

help ()
{
cat<<HELPEOF
  This hook includes cpupower tools on an archboot image.
HELPEOF
} 
