#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules 'arch/x86/kernel/cpu/cpufreq|drivers/cpufreq'
    add_binary "/usr/bin/cpupower"
    add_file "/usr/bin/cpufreq-bench_plot.sh"
    add_file "/etc/cpufreq-bench.conf"
}

help ()
{
cat<<HELPEOF
  This hook includes cpupower tools on an arch boot image.
HELPEOF
} 
