#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/net/wireless/|/net/wireless/|/net/ieee80211/|/net/mac80211/'
    apps="/usr/sbin/iwconfig /usr/sbin/iwevent /usr/sbin/iwgetid /usr/sbin/iwlist /usr/sbin/iwpriv \
          /usr/sbin/iwspy /usr/sbin/ifrename /usr/bin/b43-fwcutter /usr/sbin/wpa_cli /usr/sbin/wpa_passphrase \
	  /usr/sbin/wpa_supplicant /usr/sbin/iw /usr/bin/crda /usr/bin/regdbdump /usr/sbin/wpa_actiond /usr/sbin/rfkill"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/wpa_supplicant/wpa_supplicant.conf"
    # add zd1211 firmware files
    for i in /usr/lib/firmware/zd1211/* ; do
	add_file "$i"
    done
    # crda support
    add_file "/usr/bin/set-wireless-regdom"
    add_file "/etc/conf.d/wireless-regdom"
    add_file "/usr/lib/crda/regulatory.bin"
    # fixing licenses
    add_file "/usr/share/licenses/expat/COPYING"
    add_file "/usr/share/licenses/crda/LICENSE"
    add_file "/usr/share/licenses/wireless-regdb/LICENSE"
    add_file "/usr/share/licenses/rfkill/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes wireless on an arch boot image.
HELPEOF
}
