#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_full_dir "/usr/lib/firmware/intel-ucode"
    # fix license files
    add_file "/usr/share/licenses/intel-ucode/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes intel-ucode on an arch boot image.
HELPEOF
} 
