#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/firmware/efivars'
    add_binary "/usr/sbin/efibootmgr"
}

help ()
{
cat<<HELPEOF
  This hook includes efibootmgr on an arch boot image.
HELPEOF
}

