#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules 'drivers/video/|drivers/char/agp|i915|radeon|nouveau'
    add_binary "/sbin/v86d"
    add_file "/usr/lib/modprobe.d/uvesafb.conf" "/etc/modprobe.d/uvesafb.conf"
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook includes the framebuffer and kms subsystem on an arch boot image.
HELPEOF
}
