#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_module "pcspkr"
}

help ()
{
cat<<HELPEOF
  This hook includes the pcspkr on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
