#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_file "/usr/bin/wiki-search"
    add_full_dir "/usr/share/doc/arch-wiki/text"
}

help ()
{
cat<<HELPEOF
  This hook includes arch wiki lite on an arch boot image.
HELPEOF
} 
