#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/testdisk"
    add_binary "/usr/bin/photorec"
}

help ()
{
cat<<HELPEOF
  This hook includes testdisk on an arch boot image.
HELPEOF
} 
