#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules -f 'wireless' '/drivers/net/'
    # add staging modules
    STAGING="et131x"
    for i in $STAGING; do
        add_checked_modules "/drivers/staging/$i"
    done
    apps="/bin/dnsdomainname /usr/bin/domainname /bin/netstat /usr/bin/nisdomainname /usr/bin/ypdomainname \
          /sbin/arp /sbin/ipmaddr /sbin/iptunnel /sbin/mii-tool /sbin/nameif /sbin/plipconfig /sbin/rarp \
	  /sbin/slattach /bin/ping /bin/ping6 /usr/bin/traceroute /usr/sbin/arping /usr/sbin/clockdiff \
	  /usr/sbin/rarpd /usr/sbin/rdisc /usr/sbin/tftpd /usr/sbin/tracepath /usr/sbin/tracepath6 /sbin/route \
	  /usr/bin/dig /usr/bin/host /usr/bin/nslookup /usr/bin/nsupdate /usr/bin/telnet /usr/bin/ssh /usr/sbin/arpd \
	  /usr/sbin/ctstat /usr/sbin/genl /usr/sbin/ifstat /usr/sbin/ip /usr/sbin/lnstat /usr/sbin/nstat /usr/sbin/rtacct \
	  /usr/sbin/rtmon /usr/sbin/rtstat /usr/sbin/ss /usr/sbin/tc /usr/sbin/dhclient /usr/sbin/ifplugd \
	  /usr/sbin/ifplugstatus"
    for i in $apps; do
        add_binary "$i"
    done
    appfiles="/usr/sbin/ifcfg /usr/sbin/routef /usr/sbin/routel /usr/sbin/rtpr"
    for i in $appfiles; do
        add_file "$i"
    done    
    add_file "/sbin/dhcpcd"
    add_file "/sbin/ifenslave"
    add_file "/usr/sbin/brctl"
    add_file "/etc/rc.d/network"
    add_file "/etc/rc.d/netfs"
    add_file "/usr/share/archboot/net/etc/conf.d/dhcpcd" "/etc/conf.d/dhcpcd"
    add_file "/usr/share/archboot/net/etc/conf.d/bonding" "/etc/conf.d/bonding"
    add_file "/usr/share/archboot/net/etc/conf.d/bridges" "/etc/conf.d/bridges"
    for i in $(find /usr/lib/dhcpcd -type f); do
        add_file "$i"
    done
    add_file "/usr/share/archboot/net/etc/dhcpcd.conf" "/etc/dhcpcd.conf"
    add_dir "/var/lib/dhcpcd"
    add_file "/usr/lib/tc/q_atm.so"
    add_file "/usr/share/tc/experimental.dist"
    add_file "/usr/share/tc/normal.dist"
    add_file "/usr/share/tc/pareto.dist"
    add_file "/usr/share/tc/paretonormal.dist"
    add_file "/usr/share/archboot/net/etc/iproute2/ematch_map" "/etc/iproute2/ematch_map"
    add_file "/usr/share/archboot/net/etc/iproute2/rt_dsfield" "/etc/iproute2/rt_dsfield"
    add_file "/usr/share/archboot/net/etc/iproute2/rt_protos" "/etc/iproute2/rt_protos"
    add_file "/usr/share/archboot/net/etc/iproute2/rt_realms" "/etc/iproute2/rt_realms"
    add_file "/usr/share/archboot/net/etc/iproute2/rt_scopes" "/etc/iproute2/rt_scopes"
    add_file "/usr/share/archboot/net/etc/iproute2/rt_tables" "/etc/iproute2/rt_tables"
    # add dnssec-anchors
    add_file "/etc/trusted-key.key"
    # add dhclient support
    add_file "/sbin/dhclient-script"
    add_dir "/var/lib/dhclient"
    add_dir "/var/state/dhcp"
    # add ifplugd support
    add_file "/etc/rc.d/ifplugd"
    add_file "/etc/ifplugd/ifplugd.action"
    add_file "/usr/share/archboot/net/etc/ifplugd/ifplugd.conf" "/etc/ifplugd/ifplugd.conf"
    # fixing licenses
    add_file "/usr/share/licenses/db/LICENSE"
    add_file "/usr/share/licenses/dhcpcd/LICENSE"
    add_file "/usr/share/licenses/dhclient/LICENSE"
    add_file "/usr/share/licenses/dnsutils/LICENSE"
    add_file "/usr/share/licenses/krb5/LICENSE"
    add_file "/usr/share/licenses/openssh/LICENCE"
    add_file "/usr/share/licenses/openssl/LICENSE"
    add_file "/usr/share/licenses/sqlite/license.txt"
    add_file "/usr/share/licenses/dnssec-anchors/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the network on an arch boot image.
HELPEOF
}
