#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_file "/etc/archboot/defaults" "/usr/lib/archboot/common.sh" \
    "/usr/lib/archboot/container.sh" "/usr/bin/archboot-$(uname -m)-create-container.sh" \
    "/usr/lib/archboot/update-installer.sh"
    add_file "/usr/bin/archboot-update-installer.sh" "/usr/bin/update-installer.sh"
    add_file "/usr/share/archboot/etc/profile.d/launch-setup.sh" "/etc/profile.d/launch-setup.sh"
}

help ()
{
cat<<HELPEOF
  This hook adds basic installer files on an archboot image.
HELPEOF
}
