#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
  add_full_dir /var/cache/pacman/pkg
}

help ()
{
cat<<HELPEOF
  This hook includes /var/cache/pacman/pkg.
HELPEOF
}
