#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules 'md/dm-*'
    add_binary "/sbin/dmsetup"
    add_binary "/sbin/dmeventd"
    add_dir "/dev/mapper"
}

help ()
{
cat<<HELPEOF
  This hook includes dmraid on an arch boot image.
HELPEOF
} 
