#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary chntpw reged cpnt
}

help ()
{
cat<<HELPEOF
  This hook includes chntpw on an archboot image.
HELPEOF
} 
