#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_runscript
}

help ()
{
cat <<HELPEOF
  This hook will override advanced hooks for your system.
  Use advanced=hook1,hook2,hook3 eg. advanced=arch_encrypt,arch_mdadm
  to override the defaults.
HELPEOF
}
