#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="poff pon chat plog pppd pppdump pppoe-discovery pppstats"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/usr/lib/pppd"
    add_full_dir "/etc/ppp"
    # fix license files
    add_file "/usr/share/licenses/libpcap/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes ppp on an arch boot image.
HELPEOF
} 
