#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_all_modules -f 'aes.ko' '/crypto/|cryptoloop'
    add_binary "cryptsetup"
    # fix licenses
    add_file "/usr/share/licenses/popt/LICENSE"
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook allows for an encrypted root device on an arch boot image.
  It depends on arch_devicemapper hook.
HELPEOF
}
