#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/links"
}

help ()
{
cat<<HELPEOF
  This hook includes the links browser on an arch boot image.
HELPEOF
} 
