#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary genfstab arch-chroot pacstrap \
    archboot-binary-check.sh archboot-not-installed.sh archboot-locale.sh
    add_file "/usr/bin/archboot-setup.sh" "/usr/bin/setup"
    add_file "/usr/bin/archboot-quickinst.sh" "/usr/bin/quickinst"
    add_file "/usr/bin/archboot-copy-mountpoint.sh" "/usr/bin/copy-mountpoint.sh"
    add_file "/usr/bin/archboot-rsync-backup.sh" "/usr/bin/rsync-backup.sh"
    add_file "/usr/bin/archboot-restore-usbstick.sh" "/usr/bin/restore-usbstick.sh"
    add_full_dir "/usr/lib/archboot/installer"
    add_file "/etc/archboot/defaults"
    add_file "/usr/share/archboot/grub/archboot-background.png"
}

help ()
{
cat<<HELPEOF
  This hook includes the archboot installer,archinstaller and arch-install-scripts 
  on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
