#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary netctl-auto wifi-menu netctl
    map add_full_dir "/usr/lib/netctl/" "/etc/netctl/"
    add_file "/etc/ifplugd/netctl.action"
    # add openresolv depends
    add_binary "resolvconf"
    map add_file "/etc/resolvconf.conf" "/usr/share/licenses/openresolv/LICENSE"
    add_full_dir "/usr/lib/resolvconf/"
}

help ()
{
cat<<HELPEOF
  This hook includes the netctl package on an archboot image.
HELPEOF
}
