#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    source /etc/archboot/defaults
    # only include cachedir on booted archboot or container
    for i in "${_ISO_HOME_SOURCE}"/"${_DIR}"/*;do
        [[ ! -L "${i}" ]] && add_file "$i" "/var/cache/pacman/pkg/$(basename $i)"
    done
    # fix symlinks
    add_symlink "/var/cache/pacman/pkg/archboot.db" "/var/cache/pacman/pkg/archboot.db.tar.gz"
    add_symlink "/var/cache/pacman/pkg/archboot.files" "/var/cache/pacman/pkg/archboot.files.tar.gz"
}

help ()
{
cat<<HELPEOF
  This hook includes the archboot sources to
  /var/cache/pacman/pkg
HELPEOF
}
