#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/lshw"
    for i in "manuf oui pnpid"; do
	add_file "/usr/share/lshw/$i.txt"
    done
    add_file "/usr/share/lshw/pnpid.txt"
}

help ()
{
cat <<HELPEOF
  This hook will add lshw to your archboot image.
HELPEOF
}
