#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "dnsmasq"
    add_file "/etc/dnsmasq.conf"
    map add_dir "/var/db" "/var/lib/misc"
}

help ()
{
cat<<HELPEOF
  This hook includes dnsmasq on an archboot image.
HELPEOF
} 
