#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_full_dir "/usr/share/licenses/common"
}

help ()
{
cat<<HELPEOF
  This hook includes the common licenses on an archboot image.
HELPEOF
} 
# vim: set ft=sh ts=4 sw=4 et:
