#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_module 'sr_mod'
}

help ()
{
cat<<HELPEOF
  This hook includes the cdrom support on an arch boot image.
HELPEOF
}
