#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/lftp"
    add_binary "/usr/bin/lftpget"
    add_file "/etc/lftp.conf"
}

help ()
{
cat<<HELPEOF
  This hook includes lftp on an arch boot image.
HELPEOF
} 
