#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/pfc /usr/sbin/xl2tpd /usr/sbin/xl2tpd-control"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/etc/xl2tpd"
}

help ()
{
cat<<HELPEOF
  This hook includes xl2tpd on an arch boot image.
HELPEOF
} 
