#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/kernel/fs|loop'
    apps="/sbin/mkswap /sbin/debugreiserfs /sbin/mkreiserfs /sbin/reiserfsck /sbin/reiserfstune \
          /sbin/resize_reiserfs /sbin/badblocks /sbin/blkid /sbin/debugfs /sbin/dumpe2fs /sbin/e2fsck \
	  /sbin/e2image /sbin/e2undo /sbin/findfs /sbin/fsck /sbin/logsave /sbin/mkfs.ext2 /sbin/resize2fs \
	  /usr/bin/chattr /usr/bin/lsattr /usr/sbin/e2freefrag /usr/sbin/filefrag /usr/sbin/mkntfs \
	  /usr/sbin/ntfscp /usr/sbin/ntfsclone /usr/sbin/ntfslabel /usr/sbin/ntfsresize /usr/sbin/ntfsundelete \
	  /usr/bin/ntfscat /usr/bin/ntfscluster /usr/bin/ntfscmp /usr/bin/ntfsfix /usr/bin/ntfsinfo /usr/bin/ntfsls \
	  /sbin/jfs_debugfs /sbin/jfs_fsck /sbin/jfs_fscklog /sbin/jfs_logdump /sbin/jfs_mkfs /sbin/jfs_tune \
	  /sbin/mkfs.xfs /sbin/xfs_repair /usr/sbin/xfs_copy /usr/sbin/xfs_db /usr/sbin/xfs_growfs /usr/sbin/xfs_io \
	  /usr/sbin/xfs_logprint /usr/sbin/xfs_mdrestore /usr/sbin/xfs_quota /usr/sbin/xfs_rtcp /sbin/mkdosfs /sbin/dosfsck \
	  /sbin/dosfslabel /usr/bin/lowntfs-3g /usr/bin/ntfs-3g /sbin/mount.nfs /usr/bin/mount.cifs \
	  /usr/sbin/cifs.upcall /sbin/fsck.ext2 /sbin/fsck.ext3 /sbin/fsck.ext4 \
	  /sbin/fsck.ext4dev /sbin/e2label /sbin/tune2fs /sbin/mkfs.ext3 /sbin/mkfs.ext4 /sbin/mke2fs /sbin/fsck.jfs \
	  /sbin/mkfs.jfs /sbin/wipefs /sbin/blockdev /usr/bin/btrfs /usr/bin/btrfs-convert /usr/bin/btrfs-debug-tree \
	  /usr/bin/btrfs-find-root /usr/bin/btrfs-image /usr/bin/btrfs-map-logical /usr/bin/btrfs-restore \
	  /usr/bin/btrfs-show /usr/bin/btrfs-vol /usr/bin/btrfs-zero-log /usr/bin/btrfsck /usr/bin/btrfsctl \
	  /usr/bin/btrfstune /usr/bin/mkfs.btrfs /sbin/mkfs.nilfs2 /sbin/mount.nilfs2 /sbin/nilfs_cleanerd \
	  /sbin/umount.nilfs2 /usr/bin/chcp /usr/bin/dumpseg /usr/bin/lscp /usr/bin/lssu /usr/bin/mkcp /usr/bin/rmcp \
	  /sbin/fsck.cramfs /sbin/fsck.minix /sbin/fsfreeze /sbin/fstrim /sbin/mkfs.bfs /sbin/mkfs.cramfs \
	  /sbin/mkfs.minix"
    for i in $apps; do
        add_binary "$i"
    done
    appfiles="/usr/bin/compile_et /usr/bin/mk_cmds /sbin/fsck.xfs /usr/sbin/xfs_admin /usr/sbin/xfs_bmap \
              /usr/sbin/xfs_check /usr/sbin/xfs_freeze /usr/sbin/xfs_info /usr/sbin/xfs_metadump /usr/sbin/xfs_mkfile \
	      /usr/sbin/xfs_ncheck" 
    for i in $appfiles; do
        add_file "$i"
    done
    symlinks="/sbin/fsck.msdos /sbin/fsck.vfat /sbin/fsck.reiserfs /sbin/mkfs.vfat /sbin/mkfs.msdos \
              /usr/bin/mkfs.ntfs /sbin/mkfs.reiserfs /sbin/mount.nfs4 /usr/bin/mount.ntfs /usr/bin/mount.lowntfs-3g \
              /usr/bin/mount.ntfs-3g /sbin/umount.nfs /sbin/umount.nfs4"
    for i in $symlinks; do
        add_binary "$(which $(basename $(readlink "$i")))"
        add_symlink "$i" "$(which $(basename $(readlink "$i")))"
    done
    add_file "/etc/nilfs_cleanerd.conf"
    # fix licenses
    add_file "/usr/share/licenses/e2fsprogs/MIT-LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook is responsible for including filesystems on an arch boot image.
HELPEOF
}
