#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary vis vis-clipboard vis-complete vis-digraph vis-menu vis-open
    map add_full_dir /etc/vis /usr/share/vis /usr/lib/lua /usr/share/lua
    map add_file /usr/share/licenses/vis/LICENSE /usr/share/licenses/vis/LICENSE
}

help ()
{
cat<<HELPEOF
  This hook includes vis on an archboot image.
HELPEOF
} 
