#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_module 'cryptoloop'
}

help ()
{
cat<<HELPEOF
  This hook adds cryptoloop module on an arch boot image.
HELPEOF
}
