#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary poff pon chat plog pppd pppdump pppoe-discovery pppstats
    map add_full_dir "/usr/lib/pppd" "/etc/ppp"
    # fix license files
    add_file "/usr/share/licenses/libpcap/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes ppp on an archboot image.
HELPEOF
} 
