#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_file "/usr/share/refind/refind_x64.efi"
    add_full_dir "/usr/share/refind/drivers_x64"
    add_full_dir "/usr/share/refind/tools_x64"
    
    add_full_dir "/usr/share/refind/keys"
    add_file "/usr/share/refind/refind.conf-sample"
    
    appfiles="/usr/bin/refind-install /usr/bin/refind-mkfont /usr/bin/mkrlconf /usr/bin/mvrefind"
    for i in $appfiles; do
        add_file "$i"
    done
    
    
}

help ()
{
cat<<HELPEOF
  This hook includes refind-efi on an arch boot image.
HELPEOF
}

