#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary efivar efisecdb
}

help ()
{
cat<<HELPEOF
  This hook includes efivar on an archboot image.
HELPEOF
}

