#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "kexec"
    add_binary "vmcore-dmesg"
}

help ()
{
cat<<HELPEOF
  This hook includes kexec on an archboot image.
HELPEOF
} 
