#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    # ipw2100 support
    map add_file "/usr/lib/firmware/ipw2100-1.3-i.fw" "/usr/lib/firmware/ipw2100-1.3-p.fw" \
        "/usr/lib/firmware/ipw2100-1.3.fw" "/usr/share/licenses/ipw2100-fw/LICENSE"
    # ipw2200 support
    map add_file "/usr/lib/firmware/ipw2200-bss.fw" "/usr/lib/firmware/ipw2200-ibss.fw" \
        "/usr/lib/firmware/ipw2200-sniffer.fw" "/usr/share/licenses/ipw2200-fw/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes intel wireless on an archboot image.
HELPEOF
}
