#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    # add firmware files and licenses
    add_full_dir "/lib/firmware"
    add_full_dir "/usr/share/licenses/linux-firmware"
}

help ()
{
cat<<HELPEOF
  This hook includes linux_firmware on an arch boot image.
HELPEOF
}
