#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary nvim
    map add_full_dir /usr/share/nvim
    map add_file /usr/share/licenses/neovim/LICENSE.txt
}

help ()
{
cat<<HELPEOF
  This hook includes neovim on an archboot image.
HELPEOF
} 
