#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules 'drivers/rtc/'
}

help ()
{
cat<<HELPEOF
  This hook includes the rtc subsystem on an arch boot image.
HELPEOF
}
