#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/firmware/dmi-sysfs'
    map add_binary dmidecode biosdecode
}

help ()
{
cat<<HELPEOF
  This hook includes dmidecode on an archboot image.
HELPEOF
}

