#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/chntpw /usr/bin/reged /usr/bin/cpnt"
    for i in $apps; do
        add_binary $i
    done
}

help ()
{
cat<<HELPEOF
  This hook includes chntpw on an arch boot image.
HELPEOF
} 
