#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    ### adding config files of installation system
    for i in $(find /usr/share/archboot/base/etc/* ! -type d ! -name passwd); do
        add_file "$i" "$(echo $i | sed -e 's#/usr/share/archboot/base##g')"
    done
    add_file "/usr/share/archboot/installer_latest/etc/passwd" "/etc/passwd"
}

help ()
{
cat <<HELPEOF
  This hook sets up stripped down base for for latest image.
HELPEOF
}
