#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_full_dir "/usr/share/kbd"
    add_file /usr/bin/archboot-km.sh /usr/bin/km
    #add kbd binaries
    map add_binary dumpkeys kbd_mode chvt deallocvt fgconsole getkeycodes kbdinfo kbdrate loadunimap mapscrn openvt psfaddtable psfgettable psfstriptable psfxtable setkeycodes setleds setmetamode setvtrgb showconsolefont showkey unicode_start unicode_stop vlock
    # only add resizecons on x86_64 
    [[ "$(uname -m)" == "x86_64" ]] && add_binary resizecons
}

help ()
{
cat<<HELPEOF
  This hook includes the keymaps and fonts on an archboot image.
HELPEOF
}
