#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary dnsdomainname netstat arp ipmaddr iptunnel mii-tool nameif plipconfig rarp \
	  slattach traceroute arping clockdiff rarpd rdisc tracepath \
	  dig host nslookup telnet ssh arpd genl ifstat ctstat rtstat lnstat nstat rtacct rtmon ss \
	  tc ifplugd ifplugstatus bridge dcb devlink rdma tipc vdpa \
      ninfod ethtool elinks weechat dhcp_lease_time dhcp_release dhcp_release6 \
	  routel brctl
    # add iproute 2, add openssl helper libraries
    map add_full_dir "/usr/lib/tc" "/usr/share/tc" "/etc/iproute2" "/usr/lib/engines"
    # add dnssec-anchors
    add_file "/etc/trusted-key.key"
    # add ifplugd support
    add_full_dir "/etc/ifplugd"
    # add weechat plugins and defaults
    PLUGINS="alias exec lua relay typing buflist fifo irc xfer charset fset logger script trigger"
    for i in ${PLUGINS}; do
      add_file "/usr/lib/weechat/plugins/$i.so"
    done
    add_file "/usr/share/archboot/net/etc/weechat/irc.conf" "/etc/weechat/irc.conf"
    add_file "/usr/share/archboot/net/etc/weechat/weechat.conf" "/etc/weechat/weechat.conf"
    add_file "/usr/share/archboot/net/etc/profile.d/weechat.sh" "/etc/profile.d/weechat.sh"
    # add elinks defaults
    add_file "/usr/share/archboot/net/etc/elinks/bookmarks" "/etc/elinks/bookmarks"
    add_file "/usr/share/archboot/net/etc/profile.d/elinks.sh" "/etc/profile.d/elinks.sh"
    # fixing licenses
    map add_file "/usr/share/licenses/db/LICENSE" \
        "/usr/share/licenses/bind/LICENSE" "/usr/share/licenses/krb5/LICENSE" \
        "/usr/share/licenses/openssh/LICENCE" "/usr/share/licenses/openssl/LICENSE.txt" \
        "/usr/share/licenses/sqlite/license.txt" "/usr/share/licenses/dnssec-anchors/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the network on an archboot image.
HELPEOF
}
