#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/sbin/kexec"
    add_file "/usr/share/archboot/kexec/etc/conf.d/kexec" "/etc/conf.d/kexec"
}

help ()
{
cat<<HELPEOF
  This hook includes kexec on an arch boot image.
HELPEOF
} 
