#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_file "/usr/share/refind/refind_x64.efi"
    map add_full_dir "/usr/share/refind/drivers_x64" "/usr/share/refind/tools_x64" \
        /usr/share/refind/keys
    add_file "/usr/share/refind/refind.conf-sample"
    
    map add_binary refind-install refind-mkfont mkrlconf mvrefind
}

help ()
{
cat<<HELPEOF
  This hook includes refind-efi on an archboot image.
HELPEOF
}

