#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "efivar"
    add_binary "efisecdb"
}

help ()
{
cat<<HELPEOF
  This hook includes efivar on an archboot image.
HELPEOF
}

