#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/sbin/pptp"
    add_file "/usr/share/archboot/pptpclient/etc/ppp/options.pptp" "/etc/ppp/options.pptp"

}

help ()
{
cat<<HELPEOF
  This hook includes pptpclient on an arch boot image.
HELPEOF
} 
