#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    rm -r "/lib/firmware"
}

help ()
{
cat<<HELPEOF
  This hook cleans up binaries of archboot_firmware,
  for update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
