#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
  rm -rf /var/cache/pacman/pkg
}

help ()
{
cat<<HELPEOF
  This hook removes /var/cache/pacman/pkg
  for update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
