#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/fs/efivarfs'
    add_binary "gummiboot"
    add_full_dir "/usr/lib/gummiboot"
}

help ()
{
cat<<HELPEOF
  This hook includes gummiboot on an arch boot image.
HELPEOF
}

