#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "fsarchiver"
}

help ()
{
cat<<HELPEOF
  This hook includes fsarchiver on arch boot image.
HELPEOF
}
