#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/sound/'
}

help ()
{
cat<<HELPEOF
  This hook includes the sound subsystem on an arch boot image.
HELPEOF
}
