#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/net/wireless/|/net/wireless/|/net/ieee80211/|/net/mac80211/'
    
    if [[ "$(uname -m)" == "x86_64" ]]; then
        # add broadcom wl support
        add_module 'wl.ko'
        map add_file "/usr/lib/modprobe.d/broadcom-wl.conf" \
                     "/usr/share/licenses/broadcom-wl/LICENSE"
    fi
    # start iwd service
    add_symlink "/etc/systemd/system/multi-user.target.wants/iwd.service" "/usr/lib/systemd/system/iwd.service"
    map add_binary iwconfig iwevent iwgetid iwlist iwpriv iwspy \
        ifrename b43-fwcutter iw set-wireless-regdom rfkill hwsim iwctl iwmon set-wireless-regdom
    # add iwd and ead daemon
    add_full_dir "/usr/lib/iwd"
    # crda support
    map add_file "/etc/conf.d/wireless-regdom" "/usr/lib/crda/regulatory.bin" \
                 "/usr/lib/crda/pubkeys/sforshee.key.pub.pem"
    # fixing licenses
    map add_file "/usr/share/licenses/expat/COPYING" "/usr/share/licenses/wireless-regdb/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes wireless on an archboot image.
HELPEOF
}
