#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_file "/usr/lib/lockdown-ms/LockDown_ms.efi"
}

help ()
{
cat<<HELPEOF
  This hook includes lockdown-ms on an archboot image.
HELPEOF
}

