#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "vim"
    add_file "/etc/vimrc"
    # fix vi symlink
    add_symlink "/usr/bin/vi" "/usr/bin/vim"
    add_file "/usr/share/vim/vimfiles/archlinux.vim"
    add_file "/usr/share/vim/vim81/syntax/syntax.vim"
    add_file "/usr/share/vim/vim81/syntax/conf.vim"
    add_file "/usr/share/vim/vim81/syntax/sh.vim"
    add_file "/usr/share/vim/vim81/syntax/grub.vim"
    add_file "/usr/share/vim/vim81/syntax/manual.vim"
    add_file "/usr/share/vim/vim81/syntax/synload.vim"
    add_file "/usr/share/vim/vim81/syntax/colortest.vim"
    add_file "/usr/share/vim/vim81/syntax/syncolor.vim"
    add_file "/usr/share/vim/vim81/syntax/hitest.vim"
    add_file "/usr/share/vim/vim81/syntax/whitespace.vim"
    add_file "/usr/share/vim/vim81/syntax/modconf.vim"
    add_file "/usr/share/vim/vim81/syntax/resolv.vim"
    add_file "/usr/share/vim/vim81/syntax/fstab.vim"
    add_file "/usr/share/vim/vim81/filetype.vim"
    add_file "/usr/share/licenses/vim/license.txt"
}

help ()
{
cat<<HELPEOF
  This hook includes small version of vim on an arch boot image.
HELPEOF
} 
