#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="pppoe pppoe-connect pppoe-relay pppoe-server \
          pppoe-setup pppoe-sniff pppoe-start pppoe-status pppoe-stop"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/usr/lib/rp-pppoe"
}

help ()
{
cat<<HELPEOF
  This hook includes rp-pppoe on an arch boot image.
HELPEOF
} 
