#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
        for i in $(find /usr/share/kbd/ ! -type d ! -name "mac*"  ! -name "ppc" ! -name "ppc" ! -name "atari*" ! -name "sun*" ! -name "README*" ! -name "amiga*"); do
            add_file "$i"
        done
    add_file /usr/bin/archboot-km.sh /usr/bin/km
    #add kbd binaries
    apps="dumpkeys kbd_mode chvt deallocvt fgconsole getkeycodes kbdinfo kbdrate loadunimap mapscrn openvt psfaddtable psfgettable psfstriptable psfxtable resizecons setkeycodes setleds setmetamode setvtrgb showconsolefont showkey unicode_start unicode_stop vlock"
    for i in $apps; do
        add_binary "$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook includes the keymaps and fonts on an archboot image.
HELPEOF
}
