#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/atm|/drivers/usb/atm'
    apps="/usr/bin/aread /usr/bin/atmdiag /usr/bin/atmdump /usr/bin/awrite /usr/bin/saaldump /usr/bin/sonetdiag /usr/bin/ttcp_atm /usr/sbin/atmaddr /usr/sbin/atmarp /usr/sbin/atmarpd /usr/sbin/atmloop /usr/sbin/atmsigd /usr/sbin/atmtcp /usr/sbin/bus /usr/sbin/enitune /usr/sbin/esi /usr/sbin/ilmid /usr/sbin/lecs /usr/sbin/les /usr/sbin/mpcd /usr/sbin/zeppelin /usr/sbin/zntune"
    for i in $apps; do
        add_binary "$i"
    done
    add_dir "/etc/ppp/peers/plugins"
    add_file "/usr/share/archboot/linux_atm/etc/atmsigd.conf" "/etc/atmsigd.conf"
}

help ()
{
cat<<HELPEOF
  This hook includes linux-atm on an arch boot image.
HELPEOF
} 
