#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/net/wireless/|/net/wireless/|/net/ieee80211/|/net/mac80211/'
    # add staging wireless here
    STAGING="brcm80211 rtl8192e rtl8187se rtl8192u rtl8712 vt6655 vt6656 winbond wlan-ng"
    for i in $STAGING; do
        add_checked_modules "/drivers/staging/$i"
    done
    apps="/usr/sbin/iwconfig /usr/sbin/iwevent /usr/sbin/iwgetid /usr/sbin/iwlist /usr/sbin/iwpriv \
          /usr/sbin/iwspy /usr/sbin/ifrename /usr/bin/b43-fwcutter /usr/sbin/wpa_cli /usr/sbin/wpa_passphrase \
	  /usr/sbin/wpa_supplicant /usr/sbin/iw /sbin/crda /sbin/regdbdump /usr/sbin/wpa_actiond /usr/sbin/rfkill"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/conf.d/wireless"
    add_file "/etc/wpa_supplicant.conf"
    # add rfkill
    add_file "/etc/conf.d/rfkill"
    add_file "/etc/rc.d/rfkill"
    # add zd1211 firmware files
    for i in /usr/lib/firmware/zd1211/* ; do
	add_file "$i"
    done
    # crda support
    add_file "/etc/rc.d/wireless-regdom"
    add_file "/etc/conf.d/wireless-regdom"
    add_file "/usr/lib/crda/regulatory.bin"
    # fixing licenses
    add_file "/usr/share/licenses/expat/COPYING"
    add_file "/usr/share/licenses/dbus-core/COPYING"
    add_file "/usr/share/licenses/crda/LICENSE"
    add_file "/usr/share/licenses/wireless-regdb/LICENSE"
    add_file "/usr/share/licenses/rfkill/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes lts wireless on an arch boot image.
HELPEOF
}
