#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    ! [ -d ${TEMPDIR}/packages ] && mkdir ${TEMPDIR}/packages
    ! [ -d ${TEMPDIR}/config ] && mkdir ${TEMPDIR}/config
    cp -r /etc/archboot/packages/* ${TEMPDIR}/packages
    cp -r /etc/archboot/config/* ${TEMPDIR}/config
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook includes the addons check on an arch boot image.
HELPEOF
} 