#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_file "/usr/bin/archboot-update-installer.sh" "/usr/bin/update-installer.sh"
    add_file "/usr/bin/archboot-$(uname -m)-create-container.sh"
    add_file "/usr/share/archboot/installer_latest/etc/profile.d/latest-installer.sh" "/etc/profile.d/latest-installer.sh"
}

help ()
{
cat<<HELPEOF
  This hook reboots the latest archboot installer with package cache on an archboot image.
HELPEOF
}
