#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/sbin/lvm /sbin/lvmdump /sbin/lvmconf /sbin/vgimportclone /sbin/fsadm"
    for i in $apps; do
        add_binary "$i"
    done
    symlinks="/sbin/vgcfgbackup /sbin/vgcfgrestore /sbin/vgchange \
              /sbin/vgck /sbin/vgconvert /sbin/vgcreate /sbin/vgdisplay /sbin/vgexport /sbin/vgextend /sbin/vgimport \
	      /sbin/vgmerge /sbin/vgmknodes /sbin/vgreduce /sbin/vgremove /sbin/vgrename /sbin/vgs /sbin/vgscan \
	      /sbin/vgsplit /sbin/pvchange /sbin/pvck /sbin/pvcreate /sbin/pvdisplay /sbin/pvmove /sbin/pvremove \
	      /sbin/pvresize /sbin/pvs /sbin/pvscan /sbin/lvchange /sbin/lvconvert /sbin/lvcreate /sbin/lvdisplay \
	      /sbin/lvextend /sbin/lvmchange /sbin/lvmdiskscan /sbin/lvmsadc /sbin/lvmsar /sbin/lvreduce /sbin/lvremove \
	      /sbin/lvrename /sbin/lvresize /sbin/lvs /sbin/lvscan"
    for i in $symlinks; do
        add_binary "$(which $(basename $(readlink "$i")))"
        add_symlink "$i" "$(which $(basename $(readlink "$i")))"
    done
    add_dir "/etc/lvm/backup/"
    add_dir "/etc/lvm/archive/"
    add_file "/etc/lvm/lvm.conf"
    for i in /usr/lib/liblvm*; do
        add_file "$i"
    done
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook loads the necessary modules for an LVM2 root device 
  on an arch boot image.
  It depends on arch_devicemapper hook.
HELPEOF
}
