#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/sbin/openvpn"
    add_dir "/etc/openvpn"
    # add examples
    for i in /usr/share/openvpn/examples/*; do
        add_file "$i"
    done
    # add easy rsa
    for i in /usr/share/openvpn/easy-rsa/*; do
        add_file "$i"
    done
    # add plugins
    for i in /usr/lib/openvpn/plugins/*; do
        add_file "$i"
    done
    # fix licenses
    add_file "/usr/share/licenses/openvpn/COPYING"
}

help ()
{
cat<<HELPEOF
  This hook includes openvpn on an arch boot image.
HELPEOF
} 
