#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/sbin/lilo"
    add_file "/usr/share/archboot/lilo/etc/lilo.conf" "/etc/lilo.conf"
    # fix licenses
    add_file "/usr/share/licenses/lilo/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes lilo on an arch boot image.
HELPEOF
} 
