#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    # add firmware files and licenses
    add_dir "/lib/firmware"
}

help ()
{
cat<<HELPEOF
  This hook includes linux_firmware on an arch boot image.
HELPEOF
}
