#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary kexec vmcore-dmesg
}

help ()
{
cat<<HELPEOF
  This hook includes kexec on an archboot image.
HELPEOF
} 
