#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary hwclock tzselect
    add_full_dir "/usr/share/zoneinfo"
    add_file "/usr/bin/archboot-tz.sh" "/usr/bin/tz"
}

help ()
{
cat<<HELPEOF
  This hook includes the timezone data on an archboot image.
HELPEOF
}
