#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary pppoe pppoe-connect pppoe-relay pppoe-server \
          pppoe-setup pppoe-sniff pppoe-start pppoe-status pppoe-stop
    add_full_dir "/usr/lib/rp-pppoe"
}

help ()
{
cat<<HELPEOF
  This hook includes rp-pppoe on an archboot image.
HELPEOF
} 
