#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="smartctl smartd update-smart-drivedb"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/conf.d/smartd"
    add_file "/etc/smartd.conf"
}

help ()
{
cat<<HELPEOF
  This hook includes smartmontools on an archboot image.
HELPEOF
} 
