#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/grub-editenv /usr/bin/grub-fstest /usr/bin/grub-menulst2cfg /usr/bin/grub-mkfont \
          /usr/bin/grub-mkimage /usr/bin/grub-mklayout /usr/bin/grub-mkpasswd-pbkdf2 /usr/bin/grub-mkrelpath \
	  /usr/bin/grub-mount /usr/bin/grub-ntldr-img /usr/bin/grub-script-check /usr/sbin/grub-bios-setup \
	  /usr/sbin/grub-ofpathname /usr/sbin/grub-probe"
    for i in $apps; do
        add_binary "$i"
    done
    appfiles="/usr/bin/grub-kbdcomp /usr/bin/grub-mkrescue /usr/bin/grub-mkstandalone /usr/sbin/grub-install \
              /usr/sbin/grub-mkconfig /usr/sbin/grub-mknetdir /usr/sbin/grub-reboot /usr/sbin/grub-set-default"
    for i in $appfiles; do
        add_file "$i"
    done    
    ## add grub2 config file
    add_file "/boot/grub/grub.cfg"
    
    ## add grub-mkconfig helper scripts
    add_file "/usr/share/grub/grub-mkconfig_lib"
    add_file "/etc/default/grub"
    
    for i in $(find /etc/grub.d/* ! -type d); do
        add_file "$i"
    done
    
    for i in $(find /usr/lib/grub/x86_64-efi ! -type d); do
        add_file "$i"
    done
    
    ## No need to include /usr/lib/grub/i386-efi files in the initramfs image, reduces iso size
    
    for i in $(find /usr/lib/grub/i386-pc ! -type d); do
        add_file "$i"
    done
    
    ## add grub2 unicode font file
    add_file "/usr/share/grub/unicode.pf2"
    
}

help ()
{
cat<<HELPEOF
  This hook includes grub2 on an arch boot image.
HELPEOF
}

