#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "vim"
    add_file "/etc/vimrc"
    # fix vi symlink
    add_symlink "/usr/bin/vi" "/usr/bin/vim"
    add_file "/usr/share/vim/vimfiles/archlinux.vim"
    VIM_MODULE="syntax conf dosini sh grub manual synload colortest syncolor hitest whitespace nosyntax resolv fstab bash zsh exports passwd sysctl systemd vim"
    for i in ${VIM_MODULE}; do
        [[ -e "/usr/share/vim/vim??/syntax/$i.vim" ]] && add_file "/usr/share/vim/vim??/syntax/$i.vim"
        [[ -e "/usr/share/vim/vim??/indent/$i.vim" ]] && add_file "/usr/share/vim/vim??/indent/$i.vim"
    done
    VIM_BASIC_MODULE="defaults filetype indent indoff menu scripts synmenu"
    for i in ${VIM_BASIC_MODULE}; do
       [[ -e "/usr/share/vim/vim??/$i.vim" ]] && add_file "/usr/share/vim/vim??/$i.vim"
    done
    # fix colors
    [[ -e "/usr/share/vim/vim??/colors/lists/default.vim" ]] && add_file "/usr/share/vim/vim??/colors/lists/default.vim"
    add_file "/usr/share/licenses/vim/license.txt"
    add_full_dir "/usr/share/vim/vim??/autoload/dist"
}

help ()
{
cat<<HELPEOF
  This hook includes small version of vim on an archboot image.
HELPEOF
} 
