#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook starts the network interface and mounts the NFSDIR on an arch boot image.
HELPEOF
}
