#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="traceroute arping clockdiff tracepath dig host nslookup ssh arpd \
      genl ifstat ctstat rtstat lnstat nstat rtacct rtmon ss tc \
      bridge dcb devlink rdma tipc vdpa ethtool elinks dhcp_lease_time dhcp_release \
      dhcp_release6 brctl"
    for i in $apps; do
        rm /usr/bin/"$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook cleans up binaries of archboot_net hook,
  for update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
