#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="dnsdomainname netstat arp ipmaddr iptunnel mii-tool nameif plipconfig rarp \
	  slattach traceroute arping clockdiff rarpd rdisc tracepath \
	  dig host nslookup telnet ssh arpd genl ifstat lnstat nstat rtacct rtmon ss \
	  tc dhclient ifplugd ifplugstatus bridge dcb devlink rdma ss tipc vdpa dhcpcd \
	  ping ethtool elinks ctstat rtstat dhcp_lease_time dhcp_release dhcp_release6 \
	  routel brctl"
    for i in $apps; do
        add_binary "$i"
    done
    # add iproute 2
    add_full_dir "/usr/lib/tc"
    add_full_dir "/usr/share/tc"
    add_full_dir "/etc/iproute2"
    # add openssl helper libraries
    add_full_dir "/usr/lib/engines"
    # add dnssec-anchors
    add_file "/etc/trusted-key.key"
    # add dhclient support
    add_file "/usr/bin/dhclient-script"
    add_dir "/var/lib/dhclient"
    add_dir "/var/state/dhcp"
    # add ifplugd support
    add_full_dir "/etc/ifplugd"
    # fixing licenses
    add_file "/usr/share/licenses/db/LICENSE"
    add_file "/usr/share/licenses/dhclient/LICENSE"
    add_file "/usr/share/licenses/bind/LICENSE"
    add_file "/usr/share/licenses/krb5/LICENSE"
    add_file "/usr/share/licenses/openssh/LICENCE"
    add_file "/usr/share/licenses/openssl/LICENSE"
    add_file "/usr/share/licenses/sqlite/license.txt"
    add_file "/usr/share/licenses/dnssec-anchors/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the network on an archboot image.
HELPEOF
}
