#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules 'i915|radeon|nouveau'
}

help ()
{
cat<<HELPEOF
  This hook includes the kms subsystem on an archboot image.
HELPEOF
}
