#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/dnsmasq"
    add_file "/etc/dnsmasq.conf"
    add_file "/etc/rc.d/dnsmasq"
    add_dir "/var/db"
    add_dir "/var/lib/misc"
}

help ()
{
cat<<HELPEOF
  This hook includes dnsmasq on an arch boot image.
HELPEOF
} 
