#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="lvmdump lvmconfig vgimportclone fsadm vgcfgbackup vgcfgrestore vgchange \
          vgck vgconvert vgcreate vgdisplay vgexport vgextend vgimport vgmerge vgmknodes \
          vgreduce vgremove vgrename vgs vgscan vgsplit pvchange pvck pvcreate pvdisplay \
          pvmove pvremove pvresize pvs pvscan lvchange lvconvert lvcreate lvdisplay \
          lvextend lvmdiskscan lvmsadc lvmsar lvreduce lvremove lvrename lvresize lvs lvscan"
    for i in $apps; do
        add_binary "$i"
    done
    add_dir "/etc/lvm/backup/"
    add_dir "/etc/lvm/archive/"
    for i in /usr/lib/liblvm*; do
        add_file "$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook adds complete lvm2 to archboot image, 
  which is not covered by lvm2 hook.
HELPEOF
}
