#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_checked_modules '/drivers/char/agp/' '/drivers/gpu/drm/'
}

help ()
{
cat<<HELPEOF
  This hook includes the kms subsystem on an archboot image.
HELPEOF
}
