#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary pfc xl2tpd xl2tpd-control
    add_full_dir "/etc/xl2tpd"
}

help ()
{
cat<<HELPEOF
  This hook includes xl2tpd on an archboot image.
HELPEOF
} 
