#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/isdn/'
    apps="hisaxctrl icnctrl imon imontty ipppd ipppstats isdnctrl isdnlog mkzonedb isdnconf \
	  isdnrate isdnrep capiinfo rcapid capiinit avmcapictrl"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/isdn/callerid.conf"
    add_file "/etc/isdn/isdn.conf"
    add_file "/etc/isdn/isdnlog.isdnctrl0.options"
    add_file "/etc/isdn/isdnlog.users"
    add_file "/etc/isdn/rate.conf"
    add_file "/etc/isdn/stop"
}

help ()
{
cat<<HELPEOF
  This hook includes the isdn subsystem on an arch boot image.
HELPEOF
}
