#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/lsusb"
    add_file "/usr/share/hwdata/usb.ids"
}

help ()
{
cat<<HELPEOF
  This hook includes usbutils on an arch boot image.
HELPEOF
} 
