#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="login nologin"
    for i in $apps; do
        rm /usr/bin/"$i"
    done
    apps="mount.nfs4 umount.nfs umount.nfs4 mount.nfs setfont loadkeys mkfs.btrfs rmmod"
    for i in $apps; do
        rm /usr/bin/"$i"
    done
    #dbus files
    apps="dbus-cleanup-sockets dbus-daemon dbus-launch dbus-monitor dbus-run-session dbus-send dbus-test-tool \
          dbus-update-activation-environment dbus-uuidgen"
    for i in $apps; do
        rm /usr/bin/"$i"
    done
    #systemd files
    apps="systemd-umount busctl bootctl coredumpctl hostnamectl journalctl kernel-install localectl \
          loginctl machinectl networkctl systemctl systemd-analyze systemd-ask-password \
          systemd-cat systemd-cgls systemd-cgtop \
          systemd-delta systemd-detect-virt systemd-escape systemd-firstboot systemd-hwdb systemd-inhibit systemd-machine-id-setup \
          systemd-mount systemd-notify systemd-nspawn systemd-path systemd-resolve \
          systemd-run systemd-socket-activate systemd-stdio-bridge systemd-sysusers \
          systemd-tty-ask-password-agent timedatectl systemd-repart userdbctl homectl oomctl portablectl systemd-creds \
          systemd-cryptenroll systemd-dissect systemd-id128 systemd-sysext"
    for i in $apps; do
        rm /usr/bin/"$i"
    done
}

help ()
{
cat <<HELPEOF
  This hook cleans up binaries of archboot_base_common hook,
  for update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
