#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    cp "/boot/intel-ucode.img" "${TEMPDIR}/boot/intel-ucode.img"
    # fix license files
    add_file "/usr/share/licenses/intel-ucode/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes intel-ucode on an archboot image.
HELPEOF
} 
