#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/sbin/fsarchiver"
}

help ()
{
cat<<HELPEOF
  This hook includes fsarchiver on arch boot image.
HELPEOF
}
