#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    [ "${RUNPROGRAM}"  = "mkisolinux" ] && cp "/boot/memtest86+/memtest.bin" "${TEMPDIR}/boot/memtest"
    [ "${RUNPROGRAM}"  = "archboot-tarball-helper.sh" ] && cp "/boot/memtest86+/memtest.bin" "${TEMPDIR}/boot/memtest"
    [ "${RUNPROGRAM}"  = "mksyslinux" ] && cp "/boot/memtest86+/memtest.bin" "${TEMPDIR}/boot/memtest"
    [ "${RUNPROGRAM}"  = "mkpxelinux" ] && cp "/boot/memtest86+/memtest.bin" "${INSTALLDIR}/memtest"
}

help ()
{
cat<<HELPEOF
  This hook includes the memtest on an arch boot image.
HELPEOF
}
