#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/fs/efivarfs'
    add_checked_modules '/firmware/efivars'
    add_checked_modules '/firmware/efi_pstore'
}

help ()
{
cat<<HELPEOF
  This hook efi related kernel modules on an arch boot image.
HELPEOF
}

