#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_runscript
}

help ()
{
cat <<HELPEOF
  This hook will blacklist the pata ide subsystem, 
  if ide-legacy boot parameter is used.
HELPEOF
}
