#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/pcf2vpnc /usr/sbin/vpnc /usr/sbin/vpnc-disconnect"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/vpnc/default.conf"
    add_file "/etc/vpnc/vpnc-script"

}

help ()
{
cat<<HELPEOF
  This hook includes vpnc on an arch boot image.
HELPEOF
} 
