#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    rm -r "/lib/firmware"
}

help ()
{
cat<<HELPEOF
  This hook cleans up binaries of archboot_firmware,
  for update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
