#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="netctl-auto wifi-menu netctl"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/usr/lib/network/"
    add_full_dir "/etc/netctl/"
    add_file "/etc/ifplugd/netctl.action"
    # add openresolv depends
    add_binary "resolvconf"
    add_file "/etc/resolvconf.conf"
    add_full_dir "/usr/lib/resolvconf/"
    add_file "/usr/share/licenses/openresolv/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the netctl package on an arch boot image.
HELPEOF
}
