#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules -f 'nfp' -f 'liquidio' -f 'mellanox' -f 'wireless' -f 'bnx2x' -f 'bna' -f 'softing_cs' -f 'qed' '/drivers/net/'
    map add_binary route ip dhcpcd
    add_full_dir "/usr/lib/dhcpcd"
    # start dhcpcd on startup
    add_symlink "/etc/systemd/system/multi-user.target.wants/dhcpcd.service" "/usr/lib/systemd/system/dhcpcd.service"
    add_file "/usr/share/archboot/net/etc/system/dhcpcd@.service.d/no-wait.conf" "/etc/system/dhcpcd@.service.d/no-wait.conf"
    add_file "/etc/dhcpcd.conf"
    add_dir "/var/lib/dhcpcd"
    # fixing licenses
    add_file "/usr/share/licenses/dhcpcd/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the basic network on an archboot image.
HELPEOF
}
