#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/clamscan"
    add_binary "/usr/bin/freshclam"
    # add /var directories
    add_dir "/var/run/clamav"
    add_dir "/var/lib/"
    add_dir "/var/log/clamav"
    add_file "/usr/share/archboot/clamav/etc/clamav/freshclam.conf" "/etc/clamav/freshclam.conf"
    # add unrar support
    for i in $(pacman -Ql clamav | cut -d ' ' -f2 | grep /usr/lib/libclamunrar); do
      add_file "$i"
    done
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook includes clamav on an arch boot image.
HELPEOF
} 
