#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="dnsdomainname netstat arp ipmaddr iptunnel mii-tool nameif plipconfig rarp \
      slattach traceroute arping clockdiff rarpd rdisc tracepath \
      dig host nslookup telnet ssh arpd genl ifstat ctstat rtstat lnstat nstat rtacct rtmon ss \
      tc dhclient ifplugd ifplugstatus bridge dcb devlink rdma tipc vdpa \
      ping ninfod ethtool elinks dhcp_lease_time dhcp_release dhcp_release6 \
      routel brctl dhclient-script"
    for i in $apps; do
        rm /usr/bin/"$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook cleans up binaries of archboot_net hook,
  for update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
