#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/net/'
    apps="/usr/bin/findssl.sh /usr/bin/scp /usr/bin/sftp /usr/bin/ssh-add /usr/bin/ssh-agent \
          /usr/bin/ssh-copy-id /usr/bin/ssh-keygen /usr/bin/ssh-keyscan /usr/bin/sshd /usr/bin/xinetd \
	  /usr/bin/telnetd /usr/bin/rsync /usr/bin/exportfs /usr/bin/nfsstat /usr/bin/rpc.idmapd \
	  /usr/bin/rpc.mountd /usr/bin/rpc.nfsd /usr/bin/rpc.statd /usr/bin/rpcdebug /usr/bin/showmount \
	  /usr/bin/sm-notify /usr/bin/start-statd /usr/bin/rpcbind \
	  /usr/bin/rpcinfo /usr/bin/gss_clnt_send_err /usr/bin/gss_destroy_creds /usr/bin/rpc.gssd \
	  /usr/bin/rpc.svcgssd /bin/mountpoint"
    for i in $apps; do
        add_binary "$i"
    done
    symlinks="/usr/bin/screen /usr/bin/slogin"
    for i in $symlinks; do
        add_binary "$(which $(basename $(readlink "$i")))"
        add_symlink "$i" "$(which $(basename $(readlink "$i")))"
    done
    add_file "/etc/screenrc"
    add_file "/etc/xinetd.conf"
    add_file "/etc/xinetd.d/servers"
    add_file "/etc/xinetd.d/services"
    add_file "/etc/xinetd.d/telnet"
    add_file "/etc/ssh/ssh_config"
    add_file "/etc/ssh/sshd_config"
    add_file "/etc/ssh/moduli"
    add_file "/etc/rsyncd.conf"
    add_file "/etc/xinetd.d/rsync"
    add_file "/etc/exports"
    for i in $(find /usr/share/terminfo/ ! -type d); do
    	add_file "$i"
    done
    add_file "/usr/lib/ssh/sftp-server"
    add_file "/usr/lib/ssh/ssh-keysign"
    add_file "/usr/lib/ssh/ssh-pkcs11-helper"
    add_dir  "/var/empty"
    add_file "/etc/conf.d/nfs-common.conf"
    add_file "/etc/conf.d/nfs-server.conf"
    add_file "/etc/gssapi_mech.conf"
    add_file "/etc/idmapd.conf"
    add_file "/etc/netconfig"
    add_dir "/var/lib/nfs/sm"
    add_dir "/var/lib/nfs/sm.bak"
    add_dir "/var/lib/nfs/v4recovery"
    add_dir "/var/lib/nfs/rpc_pipefs"
    # fix licenses
    add_file "/usr/share/licenses/rpcbind/COPYING"
    add_file "/usr/share/licenses/xinetd/COPYRIGHT"
    add_file "/usr/share/licenses/libsasl/COPYING"
    add_file "/usr/share/licenses/libldap/LICENSE"
    add_file "/usr/share/licenses/nfsidmap/LICENSE"
    add_file "/usr/share/licenses/libgssglue/COPYING"

    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook includes remote tools on an arch boot image.
HELPEOF
}
