#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="/usr/bin/pacman /usr/bin/pacman-db-upgrade /usr/bin/pacman-key /usr/bin/pacsort \
          /usr/bin/pactree /usr/bin/cleanupdelta /usr/bin/makepkg /usr/bin/pacman-optimize /usr/bin/pkgdelta \
          /usr/bin/rankmirrors /usr/bin/repo-add /usr/bin/repo-elephant /usr/bin/repo-remove /usr/bin/testdb \
          /usr/bin/testpkg /usr/bin/vercmp /usr/bin/curl /usr/bin/gpg /usr/sbin/haveged"
    for i in $apps; do
        add_binary "$i"
    done
DEPENDS="initscripts wget bash coreutils cryptsetup dialog \
e2fsprogs findutils gawk grep iputils jfsutils less lvm2 mdadm kmod nano \
ncurses net-tools gnu-netcat ntfsprogs pcmciautils procps-ng psmisc reiserfsprogs sed snarf \
syslog-ng sysvinit tar util-linux which wireless_tools xfsprogs dnsutils hdparm memtest86+ \
inetutils openssh hwdetect shadow bridge-utils ifenslave cpufrequtils links \
dosfstools systemd-tools initscripts filesystem linux glibc linux-api-headers xinetd links pacman \
pacman-mirrorlist screen kbd pam dhcpcd bzip2 gcc-libs openssl zlib elfutils gpm sysfsutils \
libgcrypt libgpg-error popt kexec-tools ppp libpcap rp-pppoe lilo iptables \
ntfs-3g isdn4k-utils pciutils usbutils vpnc openvpn b43-fwcutter wpa_supplicant gzip rsync \
libarchive device-mapper cracklib nfs-utils nfsidmap readline acl attr pcre cpio archboot \
fuse libusb-compat libusbx vim vim-runtime lzo2 libsasl libldap libevent gpm sdparm pptpclient licenses \
zd1211-firmware cifs-utils dmraid \
linux-atm netcfg parted tzdata ntp v86d iw crda wireless-regdb libnl iproute2 dhclient \
syslinux mtools perl gmp krb5 sqlite db dbus-core libcap fsarchiver xz librpcsecgss \
libtirpc wipe ddrescue testdisk ifplugd libdaemon wpa_actiond rfkill libgssglue icu gptfdisk \
btrfs-progs nilfs-utils linux-firmware ipw2100-fw ipw2200-fw iana-etc chntpw \
grub-common grub-bios grub-efi-x86_64 efibootmgr file eject keyutils yp-tools \
curl smartmontools dnsmasq lftp openconnect libxml2 libproxy speedtouch tcpdump nmap lua weechat \
gnutls nettle libtasn1 bind rpcbind expat progsreiserfs glib2 freetype2 libssh2 libedit \
talloc eventlog idnkit libjpeg-turbo pth gnupg libksba libassuan pinentry dirmngr gpgme ldns \
dnssec-anchors hwids libsystemd systemd systemd-arch-units dmidecode archlinux-keyring haveged \
pambase traceroute arch-wiki-lite amd-ucode intel-ucode"


for i in $DEPENDS; do
	for k in  $(echo /var/lib/pacman/local/$i-[0-9]*-[0-9]*); do
		[ -e "$k/install" ] && add_file "$k/install"
		add_file "$k/files"
		add_file "$k/desc"
	done
done
add_dir "/var/log"
add_file "/usr/share/archboot/pacman/etc/pacman.conf" "/etc/pacman.conf"
[ "$(uname -m)" = "x86_64" ] && add_file "/usr/share/archboot/pacman/etc/makepkg.conf.x86_64" "/etc/makepkg.conf"
[ "$(uname -m)" = "i686" ] && add_file "/usr/share/archboot/pacman/etc/makepkg.conf.i686" "/etc/makepkg.conf"
add_file "/usr/share/bash-completion/completions/makepkg"
add_file "/usr/share/bash-completion/completions/pacman"
add_file "/usr/share/bash-completion/completions/pacman-key"
add_file "/usr/share/archboot/pacman/etc/pacman.d/mirrorlist" "/etc/pacman.d/mirrorlist"
add_full_dir "/usr/share/pacman/keyrings"
}

help ()
{
cat<<HELPEOF
  This hook includes the pacman on an arch boot image.
HELPEOF
}
