#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/sbin/pam_tally" 
    add_binary "/sbin/unix_chkpwd"
    add_full_dir "/etc/security"
    add_full_dir "/etc/default"
    add_full_dir "/etc/pam.d"
    add_file "/etc/environment"
    for i in $(echo /usr/lib/security/pam_*.so); do
    	add_file "$i"
    done
    for i in $(echo /usr/lib/security/pam_filter/*); do
    	add_file "$i"
    done
    #fix cracklib support!
    add_file /usr/lib/libcrack.so.2
}

help ()
{
cat<<HELPEOF
  This hook includes the pam on an arch boot image.
HELPEOF
} 