#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_binary traceroute arping clockdiff tracepath ssh arpd genl \
      ifstat ctstat rtstat lnstat nstat rtacct rtmon ss tc bridge \
      dcb devlink rdma tipc vdpa ethtool elinks weechat brctl
    # add iproute 2, add openssl helper libraries
    map add_full_dir "/usr/lib/tc" "/usr/share/tc" "/etc/iproute2" "/usr/lib/engines"
    # add iptables and nftables
    map add_file /etc/arptables.conf /etc/ebtables.conf /etc/ethertypes /etc/nftables.conf
    map add_full_dir /etc/iptables /usr/lib/xtables /usr/share/iptables /usr/share/xtables /usr/share/nftables
    map add_binary arptables arptables-nft arptables-nft-restore arptables-nft-save arptables-restore \
    arptables-save ebtables ebtables-nft ebtables-nft-restore ebtables-nft-save ebtables-restore ebtables-save \
    ip6tables ip6tables-apply ip6tables-legacy ip6tables-legacy-restore ip6tables-legacy-save ip6tables-nft \
    ip6tables-nft-restore ip6tables-nft-save ip6tables-restore ip6tables-restore-translate ip6tables-save \
    ip6tables-translate iptables iptables-apply iptables-legacy iptables-legacy-restore \
    iptables-legacy-save iptables-nft iptables-nft-restore iptables-nft-save iptables-restore \
    iptables-restore-translate iptables-save iptables-translate iptables-xml nfbpf_compile nfnl_osf \
    xtables-legacy-multi xtables-monitor xtables-nft-multi nft
    # add dnssec-anchors
    add_file "/etc/trusted-key.key"
    # add weechat plugins and defaults
    PLUGINS="alias exec lua relay typing buflist fifo irc xfer charset fset logger script trigger"
    for i in ${PLUGINS}; do
      add_file "/usr/lib/weechat/plugins/$i.so"
    done
    add_file "/usr/share/archboot/net/etc/weechat/irc.conf" "/etc/weechat/irc.conf"
    add_file "/usr/share/archboot/net/etc/weechat/weechat.conf" "/etc/weechat/weechat.conf"
    add_file "/usr/share/archboot/net/etc/profile.d/weechat.sh" "/etc/profile.d/weechat.sh"
    # add elinks defaults
    add_file "/usr/share/archboot/net/etc/elinks/bookmarks" "/etc/elinks/bookmarks"
    add_file "/usr/share/archboot/net/etc/profile.d/elinks.sh" "/etc/profile.d/elinks.sh"
    # fixing licenses
    map add_file "/usr/share/licenses/krb5/LICENSE" "/usr/share/licenses/openssh/LICENCE" \
        "/usr/share/licenses/openssl/LICENSE.txt" "/usr/share/licenses/sqlite/license.txt" \
        "/usr/share/licenses/dnssec-anchors/LICENSE" "/usr/share/licenses/db5.3/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes the additional network tools on an archboot image.
HELPEOF
}
