#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules 'arch/x86/kernel/cpu/cpufreq' 'drivers/cpufreq'
    apps="/usr/bin/cpufreq-info /usr/bin/cpufreq-set"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/usr/share/archboot/cpufreq/etc/conf.d/cpufreq" "/etc/conf.d/cpufreq"
    add_file "/etc/rc.d/cpufreq"
}

help ()
{
cat<<HELPEOF
  This hook includes cpufreq tools on an arch boot image.
HELPEOF
} 
