#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="nmap ncat nping"
    for i in $apps; do
        add_binary "$i"
    done
    add_full_dir "/usr/share/nmap"
    add_file "/usr/share/licenses/nmap/LICENSE"
}

help ()
{
cat<<HELPEOF
  This hook includes nmap on an archboot image.
HELPEOF
} 
