#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    _ARCHINSTALL_URL="https://pkgbuild.com/~tpowa/archboot-helper/archinstall/archinstall"
    _ARCHINSTALL=$(mktemp -d /var/tmp/archinstall.XXX)
    curl -s --create-dirs -L -O --output-dir "${_ARCHINSTALL}" "${_ARCHINSTALL_URL}"
    chmod 755 "${_ARCHINSTALL}/archinstall"
    add_binary "${_ARCHINSTALL}/archinstall" "/usr/bin/archinstall"
    add_file "${_SHIM}/${i}" "/usr/share/archboot/fedora-shim/${i}"
    apps="genfstab arch-chroot pacstrap \
          archboot-$(uname -m)-release.sh archboot-mktorrent.sh \
          archboot-restore-usbstick.sh isoinfo mktorrent archboot-copy-mountpoint.sh \
          archboot-rsync-backup.sh archboot-binary-check.sh"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/usr/bin/archboot-setup.sh" "/usr/bin/setup"
    add_file "/usr/bin/archboot-quickinst.sh" "/usr/bin/quickinst"
    # only include cachedir on booted archboot or container
    if [[ -e "/etc/hostname" ]]; then
        [[ "$(cat /etc/hostname)" == "archboot" ]] && add_full_dir "/var/cache/pacman/pkg"
    else
        add_full_dir "/var/cache/pacman/pkg"
    fi
}

help ()
{
cat<<HELPEOF
  This hook includes the archboot installer,archinstaller and arch-install-scripts 
  on an archboot image.
HELPEOF
}
