#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    ! [ -d "${TEMPDIR}/arch/" ] && mkdir -p ${TEMPDIR}/arch/
    add_file "/usr/share/archboot/installer/setup" "/arch/setup"
    add_file "/usr/share/archboot/installer/quickinst" "/arch/quickinst"
    DOCS=$(mktemp /tmp/docs.XXXX)
    cp -f /usr/share/archboot/installer/archboot.txt ${DOCS}
    gzip -9 ${DOCS}
    add_file "${DOCS}.gz" "/arch/archboot.txt.gz" 
    add_dir "/src" 
    cp /usr/share/archboot/installer/archboot.txt ${TEMPDIR}/arch/archboot.txt
    add_file "/usr/bin/genfstab"
    add_file "/usr/bin/arch-chroot"
    add_file "/usr/bin/pacstrap"
}

help ()
{
cat<<HELPEOF
  This hook includes the archboot installer and arch-install-scripts 
  on an arch boot image.
HELPEOF
}
