#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "/usr/bin/logger"
    add_file "/etc/udev/udev.conf"
    add_file /usr/lib/modprobe.d/usb-load-ehci-first.conf
    add_symlink "/usr/bin/udevd" "../lib/systemd/systemd-udevd"
    # add rule files
    add_full_dir /usr/lib/udev
    add_runscript
}

help ()
{
cat <<HELPEOF
  This hook includes udevd and rule files.
HELPEOF
}
