#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_all_modules -f '_cs|b44|broadcom/bnx2x|brocade|cavium|chelsio|cisco|netronome|mellanox|myricom|qlogic|qualcomm' '/drivers/net/ethernet|/net/ipv4|/net/ipv6|/drivers/net/usb'
    map add_binary ip getent ping wget
    add_file /usr/bin/archboot-net.sh /usr/bin/net
    # start dhcpcd on startup
    add_file "/usr/share/archboot/net/etc/systemd/network/10-wired-auto-dhcp.network" "/etc/systemd/network/10-wired-auto-dhcp.network"
    add_file /etc/wgetrc
}

help ()
{
cat<<HELPEOF
  This hook includes the basic network on an archboot image.
HELPEOF
}
# vim: set ft=sh ts=4 sw=4 et:
