#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    # add firmware files and licenses
    map add_full_dir "/lib/firmware" "/usr/share/licenses/linux-firmware"
    rm -r "/lib/firmware"
}

help ()
{
cat<<HELPEOF
  This hook includes linux-firmware on an update installer routine.
  DO NOT USE ON REGULAR SYSTEM!.
HELPEOF
}
