#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/atm|/drivers/usb/atm'
    map add_binary aread atmdiag atmdump awrite saaldump sonetdiag ttcp_atm atmaddr atmarp atmarpd atmloop atmsigd \
          atmtcp bus enitune esi ilmid lecs les mpcd zeppelin zntune
    add_dir "/etc/ppp/peers/plugins"
    add_file "/etc/atmsigd.conf"
}

help ()
{
cat<<HELPEOF
  This hook includes linux-atm on an archboot image.
HELPEOF
} 
