#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="lvmdump lvmconfig vgimportclone fsadm"
    for i in $apps; do
        add_binary "$i"
    done
symlinks="/usr/bin/vgcfgbackup /usr/bin/vgcfgrestore /usr/bin/vgchange \
          /usr/bin/vgck /usr/bin/vgconvert /usr/bin/vgcreate /usr/bin/vgdisplay /usr/bin/vgexport /usr/bin/vgextend /usr/bin/vgimport \
	  /usr/bin/vgmerge /usr/bin/vgmknodes /usr/bin/vgreduce /usr/bin/vgremove /usr/bin/vgrename /usr/bin/vgs /usr/bin/vgscan \
	  /usr/bin/vgsplit /usr/bin/pvchange /usr/bin/pvck /usr/bin/pvcreate /usr/bin/pvdisplay /usr/bin/pvmove /usr/bin/pvremove \
	  /usr/bin/pvresize /usr/bin/pvs /usr/bin/pvscan /usr/bin/lvchange /usr/bin/lvconvert /usr/bin/lvcreate /usr/bin/lvdisplay \
	  /usr/bin/lvextend /usr/bin/lvmdiskscan /usr/bin/lvmsadc /usr/bin/lvmsar /usr/bin/lvreduce /usr/bin/lvremove \
	  /usr/bin/lvrename /usr/bin/lvresize /usr/bin/lvs /usr/bin/lvscan"
    for i in $symlinks; do
        add_binary "$(which $(basename $(readlink "$i")))"
        add_symlink "$i" "$(which $(basename $(readlink "$i")))"
    done
    add_dir "/etc/lvm/backup/"
    add_dir "/etc/lvm/archive/"
    for i in /usr/lib/liblvm*; do
        add_file "$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook adds complete lvm2 to archboot image, 
  which is not covered by lvm2 hook.
HELPEOF
}
