#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_checked_modules '/drivers/isdn/'
    apps="/usr/bin/hisaxctrl /usr/bin/icnctrl /usr/bin/imon /usr/bin/imontty /usr/bin/ipppd \
          /usr/bin/ipppstats /usr/bin/isdnctrl /usr/bin/isdnlog /usr/bin/mkzonedb /usr/bin/isdnconf \
	  /usr/bin/isdnrate /usr/bin/isdnrep /usr/bin/capiinfo /usr/bin/rcapid /usr/bin/capiinit \
	  /usr/bin/avmcapictrl"
    for i in $apps; do
        add_binary "$i"
    done
    add_file "/etc/isdn/callerid.conf"
    add_file "/etc/isdn/isdn.conf"
    add_file "/etc/isdn/isdnlog.isdnctrl0.options"
    add_file "/etc/isdn/isdnlog.users"
    add_file "/etc/isdn/rate.conf"
    add_file "/etc/isdn/stop"
}

help ()
{
cat<<HELPEOF
  This hook includes the isdn subsystem on an arch boot image.
HELPEOF
}
