#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_full_dir "/usr/share/licenses/common"
}

help ()
{
cat<<HELPEOF
  This hook includes the common licenses on an arch boot image.
HELPEOF
} 
