#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "openvpn"
    add_dir "/etc/openvpn"
    # add examples
    for i in /usr/share/openvpn/examples/*; do
        add_file "$i"
    done
    # add plugins
    for i in /usr/lib/openvpn/plugins/*; do
        add_file "$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook includes openvpn on an arch boot image.
HELPEOF
} 
