#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="chntpw reged cpnt"
    for i in $apps; do
        add_binary "$i"
    done
}

help ()
{
cat<<HELPEOF
  This hook includes chntpw on an archboot image.
HELPEOF
} 
