#!/bin/bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    apps="lvm lvmdump lvmconf vgimportclone fsadm lvmetad"
    for i in $apps; do
        add_binary "$i"
    done
    symlinks="vgcfgbackup vgcfgrestore vgchange \
              vgck vgconvert vgcreate vgdisplay vgexport vgextend vgimport \
	      vgmerge vgmknodes vgreduce vgremove vgrename vgs vgscan \
	      vgsplit pvchange pvck pvcreate pvdisplay pvmove pvremove \
	      pvresize pvs pvscan lvchange lvconvert lvcreate lvdisplay \
	      lvextend lvmchange lvmdiskscan lvmsadc lvmsar lvreduce lvremove \
	      lvrename lvresize lvs lvscan"
    for i in $symlinks; do
        add_binary "$(which $(basename $(readlink "$i")))"
        add_symlink "$i" "$(which $(basename $(readlink "$i")))"
    done
    add_dir "/etc/lvm/backup/"
    add_dir "/etc/lvm/archive/"
    add_file "/etc/lvm/lvm.conf"
    for i in /usr/lib/liblvm*; do
        add_file "$i"
    done
    add_runscript
}

help ()
{
cat<<HELPEOF
  This hook loads the necessary modules for an LVM2 root device 
  on an arch boot image.
  It depends on arch_devicemapper hook.
HELPEOF
}
