#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_binary "lsusb"
    add_file "/usr/share/hwdata/usb.ids"
}

help ()
{
cat<<HELPEOF
  This hook includes usbutils on an archboot image.
HELPEOF
} 
