#!/usr/bin/env bash
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    map add_file "/etc/archboot/defaults" "/usr/lib/archboot/common.sh" \
    "/usr/lib/archboot/container.sh" "/usr/bin/archboot-$(uname -m)-create-container.sh" \
    "/usr/lib/archboot/login.sh"
    add_full_dir "/usr/lib/archboot/update-installer"
    add_file "/usr/bin/archboot-update-installer.sh" "/usr/bin/update-installer"
    add_file "/usr/share/archboot/gpg/tpowa.gpg"
    add_symlink "/etc/profile.d/zz-archboot-login.sh" "/usr/lib/archboot/login.sh"
}

help ()
{
cat<<HELPEOF
  This hook adds basic installer files on an archboot image.
HELPEOF
}
