#!/usr/bin/env bash
# SPDX-License-Identifier: GPL-2.0-only
# Created by Tobias Powalowski <tpowa@archlinux.org>

build ()
{
    add_all_modules -f 'media' '/platform/'
}

help ()
{
cat<<HELPEOF
  This hook adds the necessary modules for a platform device.
HELPEOF
}
 
# vim: set ft=sh ts=4 sw=4 et:
