#!/usr/bin/bash
# SPDX-License-Identifier: GPL-2.0-only
# created by Tobias Powalowski <tpowa@archlinux.org>
# mount kernel filesystems
mount -t proc proc /proc -o nosuid,noexec,nodev
mount -t sysfs sys /sys -o nosuid,noexec,nodev
mount -t devtmpfs dev /dev -o mode=0755,nosuid
mount -t tmpfs run /run -o nosuid,nodev,mode=0755
if [ -e /sys/firmware/efi ]; then
    mount -t efivarfs efivarfs /sys/firmware/efi/efivars -o nosuid,nodev,noexec
fi
# initialize udev
kmod static-nodes --format=tmpfiles --output=/run/tmpfiles.d/kmod.conf
systemd-tmpfiles --prefix=/dev --create --boot
/usr/lib/systemd/systemd-udevd --daemon --resolve-names=never &>/dev/null
udevadm trigger --action=add --type=subsystems
udevadm trigger --action=add --type=devices
udevadm settle
udevadm control --exit
udevadm info --cleanup-db
echo -e "\e[1mInitializing\e[m \e[36mArchboot\e[m \e[1m- Arch Linux Environment:\e[m"
# it needs one echo before, in order to reset the consolefont!
setfont consolefont.psf.gz -C /dev/console
echo -e "\e[1mStep 1/3:\e[m Initializing /dev/zram0..."
modprobe zram
echo "zstd" >/sys/block/zram0/comp_algorithm
echo "4G" >/sys/block/zram0/disksize
echo -e "\e[1mStep 2/3:\e[m Initializing btrfs on /dev/zram0..."
mkfs.btrfs /dev/zram0 &>/dev/null
# use discard to get free RAM on delete!
mount -o discard /dev/zram0 /new_root &>/dev/null
if ! mount UUID=1234-ABCD /mnt &>/dev/null; then
    mkdir /cdrom
    mount /dev/sr0 /cdrom &>/dev/null
    mount /cdrom/efi.img /mnt &>/dev/null || /bin/sh
fi
cd new_root
echo -e "\e[1mStep 3/3:\e[m Initializing /new_root..."
bsdcpio -i </mnt/boot/initramfs-$(uname -m).img  &>/dev/null
exec switch_root /new_root /init "$@"

# vim: set ft=sh ts=4 sw=4 et:
